### PR TITLE
AVM-Plugin: Added Exception-Handling in Call-Monitor and enhanced re-connect capabilities (after fritzbox-reboot)

### PR DESCRIPTION
**Pull request by jentz1986**

### CODE REVIEW

**Comment by psilo909** [comment]
i currently cannot understand the last modification in commit, which was done to method  get_hosts(self, only_active) ???

**Comment by jentz1986** [comment]
Definitely does not cover the power failure case. But in my case Fritzbox and NAS are attached to the same UPS... And it would be possible to reconnect using some logic, e.g. called every hour, checking whether there is a call going on and then doing a reconnect (of the monitor).
From my perspective there is no other way to identify that a failure of any kind has occured... I will check if there is something which I have not seen so far...

**Comment by psilo909** [comment]
even with the same ups i experienced crashes of my old fritzbox devices after a longer runtime. in that case i rebooted the box via pulling the power supply. 

one could in theory check if web requests cause an exception and reconnect the call monitor in that case, when the first request succeeds again. but this requires more rework..

**Comment by jentz1986** [comment]
With this code it would already perform a connect automatically (in update-cycle) if the connection is detected to be down but the callmonitor is activated.

So basically whenever there is an exception caught with an own initiated request you just have to disconnect the callmonitor. It will then be started again the moment the update-cycle strikes. Could be an approach...
Worst case here: 5min downtime.

**Comment by psilo909** [comment]
@jentz1986 where do you do that? i only see a disconnect (which would start a new connect) in the reboot function. this one is not called every 5 minutes?

**Comment by jentz1986** [comment]
so far ...  so right ;-) That's why I wrote "you just have to disconnect the callmonitor".

**Comment by jentz1986** [comment]
In this case there is no difference between would and will. But let me clarify this matter here. You can set the callmonitor active in configuration (general). And in addition you have the actual status of the callmonitor object that is actively listening or not. These two do not neccessarily be of the same status. Generally active but not listening would mean: You should listen, but you don't. If this condition is given, then the last line of the update_cycle reconnects.

I did some testing: I just disconnected the FritzBox (7490, v07.01) from my LAN (UniFi Switch 8 POE-60W v3.9.27.8537, TP-Link SG1016DE v1, Synology DS415+), so the Box was running and the rest of the network as well, but no connection between them. Then I called myself. Phone rings, no display on my RTR (surprise ;-) ). If left the connection open for several minutes and called several times. Then I reconnected the Box again. Et voila: All my calls were logged into the SHNG log, with difference in timestamps between call-occurance and logging-time. So "network down" does not kill the callmonitor. I don't know how long it is cached and how much, but my expectation would be either the network is up after few seconds (e.g. when re-plugging) or you need new hardware anyway, and then forget about the lost call notifications...

Next test: Power Down... But beforehand I want to do some x-mas deco preparations.

**Comment by jentz1986** [comment]
Hmmm 
Power Down at 14:40, 
Power Up at 14:46, 
online at 14:48, 
call at 14:49:

`2018-12-12 14:38:06 CET DEBUG    __init__          plugins.avm_fritzbox.update Starting update loop for instance fritzbox  --  (__init__.py:_update_loop:617)
2018-12-12 14:38:06 CET DEBUG    __init__          plugins.avm_fritzbox.update Accessing DeviceInfo reponse cache for action GetInfo!  --  (__init__.py:_update_fritz_device_info:1566)
2018-12-12 14:38:06 CET DEBUG    __init__          plugins.avm_fritzbox.update Accessing DeviceInfo reponse cache for action GetInfo!  --  (__init__.py:_update_fritz_device_info:1566)
2018-12-12 14:38:06 CET DEBUG    __init__          plugins.avm_fritzbox.update Accessing DeviceInfo reponse cache for action GetInfo!  --  (__init__.py:_update_fritz_device_info:1566)
2018-12-12 14:38:06 CET DEBUG    __init__          plugins.avm_fritzbox.update MonitoringService: Connect called while listen active  --  (__init__.py:connect:73)
2018-12-12 14:43:06 CET DEBUG    __init__          plugins.avm_fritzbox.update Starting update loop for instance fritzbox  --  (__init__.py:_update_loop:617)
2018-12-12 14:43:16 CET ERROR    __init__          plugins.avm_fritzbox.update Exception when sending POST request: HTTPSConnectionPool(host='192.168.159.1', port=49443): Read timed out. (read timeout=10)  --  (__init__.py:_update_fritz_device_info:1562)
2018-12-12 14:43:18 CET ERROR    __init__          plugins.avm_fritzbox.update Exception when sending POST request: HTTPSConnectionPool(host='192.168.159.1', port=49443): Max retries exceeded with url: /upnp/control/deviceinfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd2000b67f0>: Failed to establish a new connection: [Errno 113] Keine Route zum Zielrechner',))  --  (__init__.py:_update_fritz_device_info:1562)
2018-12-12 14:43:21 CET ERROR    __init__          plugins.avm_fritzbox.update Exception when sending POST request: HTTPSConnectionPool(host='192.168.159.1', port=49443): Max retries exceeded with url: /upnp/control/deviceinfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd1dc060668>: Failed to establish a new connection: [Errno 113] Keine Route zum Zielrechner',))  --  (__init__.py:_update_fritz_device_info:1562)
2018-12-12 14:43:24 CET ERROR    __init__          plugins.avm_fritzbox.update Exception when sending POST request: HTTPSConnectionPool(host='192.168.159.1', port=49443): Max retries exceeded with url: /upnp/control/deviceinfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd1dc0604a8>: Failed to establish a new connection: [Errno 113] Keine Route zum Zielrechner',))  --  (__init__.py:_update_fritz_device_info:1562)
2018-12-12 14:43:24 CET DEBUG    __init__          plugins.avm_fritzbox.update MonitoringService: Connect called while listen active  --  (__init__.py:connect:73)
2018-12-12 14:48:06 CET DEBUG    __init__          plugins.avm_fritzbox.update Starting update loop for instance fritzbox  --  (__init__.py:_update_loop:617)
2018-12-12 14:48:10 CET DEBUG    __init__          plugins.avm_fritzbox.update Accessing DeviceInfo reponse cache for action GetInfo!  --  (__init__.py:_update_fritz_device_info:1566)
2018-12-12 14:48:10 CET DEBUG    __init__          plugins.avm_fritzbox.update Accessing DeviceInfo reponse cache for action GetInfo!  --  (__init__.py:_update_fritz_device_info:1566)
2018-12-12 14:48:10 CET DEBUG    __init__          plugins.avm_fritzbox.update Accessing DeviceInfo reponse cache for action GetInfo!  --  (__init__.py:_update_fritz_device_info:1566)
2018-12-12 14:48:10 CET DEBUG    __init__          plugins.avm_fritzbox.update MonitoringService: Connect called while listen active  --  (__init__.py:connect:73)`

**Comment by psilo909** [comment]
i accept the PR as i tested for some time now and reviewed code.. i will try to add disconnects to the execption handling and add a "Lock" variable to stopp logging errors as soon as the first request failed until the next request succeeds. but i doubt this will be possible until the next release. will have to wait until spring

**Pull request merged**
