### PR TITLE
Enocean: restructure learn methods

### PR DESCRIPTION
**Pull request by hasenradball**
Changes:
-    Line 447: move comment in front of logic
-     move all learn methods in one "Learn methods section" at the end of the file
-     correction of payload for send learn switch
-     restructure existing learn methods like that:
1.   define RORG
2.     define PAYLOAD
3.     send(RORG, PAYLOAD)
4.     logger(RORG, PAYLOAD)

    The benefit is the payload can be used directly in the send command an the logger.
    logger-format: rorg = a5 / payload = [0xe0, 0x40, 0x0d, 0x80]

benefit of this changes is to define only one learn methods for future improvements and calculate in a switch...case construction thr rorg and payload.

### CODE REVIEW

**Comment by hasenradball** [comment]
Conlicts were solved.

**Comment by ohinckel** [comment]
@hasenradball new conflicts inthis PR. Can you please have a look again?

Sorry for taking so long unil this gets merged. But I don't know if this PR does not introduce a new bug since I'm not able to test it. Maybe @drgeh could help here and have a look on it?

**Comment by hasenradball** [comment]
Hello Ohinckel,

 

I can suggest to implement my changes with the actual changes, but so I expect a diff will be maybe not possible.

But I will try before, so bthat all functionality works.

 

Is this ok for you?

 

If not I will do this by myself but I will never provide a update or new features an it takes nearly a half a year if anyone will have a look on it and by this time many oder PR were accepted.

 

 

Mit freundlichem Gruß

 

Frank Häfele

Habichtweg 4

74343 Sachsenheim

 

Telefon: +49 (7147) 2769779

Telefax: +49 (7147) 2764259

Email: mail@frankhaefele.de

 

Von: ohinckel [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. September 2017 10:42
An: smarthomeNG/plugins
Cc: Frank Häfele; Mention
Betreff: Re: [smarthomeNG/plugins] Enocean: restructure learn methods (#44)

 

@hasenradball <https://github.com/hasenradball>  new conflicts inthis PR. Can you please have a look again?

Sorry for taking so long unil this gets merged. But I don't know if this PR does not introduce a new bug since I'm not able to test it. Maybe @DrGEH <https://github.com/drgeh>  could help here and have a look on it?

**Comment by ohinckel** [comment]
I reviewd the conflicts and this seems to be easy to resolve. Changes came from #70, #71 and #77.

Could you do a `git fetch` and `git rebase` (and `git rebase --continue`) with `develop` branch? This way you can provide the changes with resolving the conflicts in a clean history.

**Comment by hasenradball** [comment]
Hello Ohinckel,

 

I wanna understand your idea.

 

You want I should make a fetch (to get the actual files  from the server ) and to a rebase with then to place it in the develop branch?

Right?

 

And then we will be able to accept my changes?

 

Right? 

 

Von: ohinckel [mailto:notifications@github.com] 
Gesendet: Sonntag, 29. Oktober 2017 20:04
An: smarthomeNG/plugins
Cc: Frank Häfele; Mention
Betreff: Re: [smarthomeNG/plugins] Enocean: restructure learn methods (#44)

 

I reviewd the conflicts and this seems to be easy to resolve. Changes came from #70 <https://github.com/smarthomeNG/plugins/pull/70> , #71 <https://github.com/smarthomeNG/plugins/pull/71>  and #77 <https://github.com/smarthomeNG/plugins/pull/77> .

Could you do a git fetch and git rebase (and git rebase --continue) with develop branch? This way you can provide the changes with resolving the conflicts in a clean history.

**Comment by ohinckel** [comment]
Just do the following in your branch:
* git fetch vendor develop
* git rebase / git rebase --continue (in case of the conflict after resolving them)

You can also create a new branch from an up-to-date `develop` and integrate your change in this.

**Comment by hasenradball** [comment]
Hello,

Ok i will integrate my changes in a new branch, but it will take a few days.

Mit freundlichen Grüßen

Frank Häfele

**Comment by hasenradball** [comment]
A new pr is in the pipeline...

Mit freundlichen Grüßen

Frank Häfele

**Comment by ohinckel** [comment]
If you create a new PR I guess we can close this PR for the moment.

But has PR #87 something to do with this PR? Can we close this too?

**Comment by hasenradball** [comment]
Hello,

Pr 87 is the result we discussed. In this pr i merged my changes in the actual develop.

Wenn pr 87 will be accepted I can close pr 44.

Mit freundlichen Grüßen

Frank Häfele

**Comment by hasenradball** [comment]
Hello,

 

what about the PR#87 now can we merge into the actual develop?

An then close the PR#44?

 

The changes are the same as described but pr#87 is based on the actual develop.

 

Von: ohinckel [mailto:notifications@github.com] 
Gesendet: Mittwoch, 8. November 2017 21:19
An: smarthomeNG/plugins
Cc: Frank Häfele; Mention
Betreff: Re: [smarthomeNG/plugins] Enocean: restructure learn methods (#44)

 

If you create a new PR I guess we can close this PR for the moment.

But has PR #87 <https://github.com/smarthomeNG/plugins/pull/87>  something to do with this PR? Can we close this too?

**Comment by ohinckel** [comment]
Too bad that the other PR's diff looks that large (I guess due to newline character/endings changes). So I can't say if it is OK or not. Maybe @aschwith can have a look at this and test.

I'll close this now, any further discussion can be done in the other PR.

**Comment by hasenradball** [comment]
Hey make an diff with an professional tool.
Then you will se there are only these changes I decribed.
Which pr will you close? 44?

Mit freundlichen Grüßen

Frank Häfele

**Comment by ohinckel** [comment]
Of course I can create a diff with other tools, but I prefer to see the changes here. Otherwise:
* all other contributors/members need to do this manually, too
* it will become hard to find out introduced bugs when all diffs are such great
* the history will get really bad since all lines will getting changed all the time

I closed #44.

**Pull request closed without merging**
