### PR TITLE
hue2: more verbose error messages

### PR DESCRIPTION
**Pull request by CaeruleusAqua**
Log was not showing any exception message

### CODE REVIEW

**Comment by msinn** [comment]
Hi,
this PR contains modifications to multiple plugins (not only for the hue2 plugin). That's why I can't accept it. To be accepted. To be acceptable, it should be placed again, containing only changes to the plugin specified in the title.

Btw.: The PR doesn't make the error messages any more verbose, at least on a Hue bridge. In contrast, it cuts out part of the info.

For 
```self.logger.error(f"update_light_from_item: item {plugin_item['item'].id()} - qhue exception '{e}'")```
The Log Entry is
```qhue exception 'QhueException: 201 -> parameter, bri, is not modifiable. Device is set to off.'```

While the log message for
```self.logger.error(f"update_light_from_item: item {plugin_item['item'].id()} - qhue exception '{e.message}'")```
is
```qhue exception 'parameter, bri, is not modifiable. Device is set to off.'```

So it cuts out the exception type (which is not really needed in the log) and the error number, which makes it easier to find the error documentation in the Philips API docu.

**Comment by CaeruleusAqua** [comment]
The change must have slipped in somehow during merge. I will make the pull request again.

At least for me the change makes sense, but I use deconz and not the original hue bridge.
Without this patch it has logged only the QhueException and the error number. So without a message!

**Comment by msinn** [comment]
Maybe a parameter could/should be added, if  deconz (or: dekonz or a Hue bridge v1) is used.
This could be helpful, since I am going to start implementing API v2 support, which is not supported by dekonz and bridge v1.

I am doing that before I push my actual modifications toe the hur2 plugin.
At the moment I have completed  modification to the 'dict' function: For lights, the actual state is read into the 'dict' Item. This way I can use die 'dict' function in scenes which have learning enabled.

So: You can just close this PR and wait for the new version I am going to push.

**Comment by msinn** [comment]
Kannst Du mir noch sagen, was bei Dir als Modell Name angezeigt wird?


Capto_Capture 2022-12-02_02-58-37_PM

**Comment by CaeruleusAqua** [comment]
Philips hue bridge 2015

**Comment by CaeruleusAqua** [comment]
screenshot

**Comment by msinn** [comment]
Too bad. Identifiziert sich den deconz auch als v2 mit API 1.5x.x?

**Comment by msinn** [comment]
Ok,
dann kann ich das nur an der API Version 1.16 erkennen. Das ist die API Version der v1 Bridge, die sich aber als 
Philips hue bridge 2012
identifiziert.

- Philips hue bridge 2012 mit API 1.16 -> Philips v1
- Philips hue bridge 2015 mit API 1.16 -> DeConz
- Philips hue bridge 2015 mit API 1.5x -> Philips v2

**Comment by CaeruleusAqua** [comment]
Sorry, Frau kommt gerade mit dem Kind nach hause, ich schaue heute Abend nochmal:

Folgendes spukt die API aus:
//192.168.178.71:8080/api/F98307BC04/config

                    {
    "UTC": "2022-12-02T14:26:16",
    "announceinterval": 45,
    "announceurl": "https://phoscon.de/discover",
    "apiversion": "2.19.01",
    "bridgeid": "00212EFFFF04DB53",
    "datastoreversion": "93",
    "devicename": "ConBee II",
    "dhcp": true,
    "disablePermitJoinAutoOff": false,
    "discovery": true,
    "factorynew": false,
    "fwneedupdate": false,
    "fwupdatestate": "idle",
    "fwversion": "0x26720700",
    "gateway": "192.168.178.1",
    "groupdelay": 50,
    "homebridge": "not-available",
    "ipaddress": "192.168.178.71",
    "lightlastseeninterval": 60,
    "linkbutton": false,
    "localtime": "2022-12-02T14:26:16",
    "mac": "b4:2e:99:54:a3:6e",
    "modelid": "deCONZ",
    "name": "Phoscon-GW",
    "netmask": "255.255.255.0",
    "networkopenduration": 180,
    "ntp": "synced",
    "otauactive": false,
    "otaustate": "off",
    "panid": 34894,
    "permitjoin": 0,
    "permitjoinfull": 0,
    "port": 8080,
    "portalservices": false,
    "proxyaddress": "none",
    "proxyport": 0,
    "replacesbridgeid": null,
    "rfconnected": true,
    "runmode": "systemd/headless",
    "starterkitid": "",
    "swcommit": "ac888e70b2968d7fa80a8c66e35ac06e4dd5c5e1",
    "swupdate": {
        "notify": false,
        "text": "",
        "updatestate": 0,
        "url": "",
        "version": "2.19.01"
    },
    "swupdate2": {
        "autoinstall": {
            "on": false,
            "updatetime": ""
        },
        "bridge": {
            "lastinstall": "2022-10-22T16:23:30",
            "state": "noupdates"
        },
        "checkforupdate": false,
        "lastchange": "",
        "state": "noupdates"
    },
    "swversion": "2.19.01",
    "system": "other",
    "timeformat": "24h",
    "timezone": "Europe/Berlin",
    "updatechannel": "stable",
    "uuid": "c14ece50-ad71-48ee-808b-b46928250f92",
    "websocketnotifyall": true,
    "websocketport": 443,
    "whitelist": {
        "042DC3A196": {
            "create date": "2021-09-13T19:02:58",
            "last use date": "2022-12-02T14:26:16",
            "name": "SmartHomeNG#smarthomeng"
        },
        "067B10C922": {
            "create date": "2021-10-21T18:53:18",
            "last use date": "2021-10-28T06:59:00",
            "name": "Phoscon#B360x362"
        },
        "0F7D702390": {
            "create date": "2022-02-17T20:01:43",
            "last use date": "2022-02-19T17:39:43",
            "name": "Phoscon#B1745x852"
        },
        "1257815C6C": {
            "create date": "2022-11-16T23:33:47",
            "last use date": "2022-11-16T23:39:26",
            "name": "Phoscon#B360x408"
        },
        "1434A43BC6": {
            "create date": "2021-09-27T19:52:30",
            "last use date": "2021-10-01T21:22:45",
            "name": "Phoscon#B360x362"
        },
        "1716044EEE": {
            "create date": "2021-12-22T15:38:26",
            "last use date": "2021-12-29T08:59:56",
            "name": "Phoscon#B360x362"
        },
        "1A088C4E2B": {
            "create date": "2021-09-04T20:00:11",
            "last use date": "2022-02-19T23:37:44",
            "name": "smarthomeng"
        },
        "22C555F545": {
            "create date": "2021-02-01T13:51:37",
            "last use date": "2021-02-02T14:53:19",
            "name": "Phoscon#B3440x1297"
        },
        "2452B8DF12": {
            "create date": "2021-09-03T21:41:33",
            "last use date": "2021-09-03T21:46:17",
            "name": "Phoscon#B1920x937"
        },
        "2D45B96D11": {
            "create date": "2021-09-17T14:29:08",
            "last use date": "2021-09-23T19:52:39",
            "name": "Phoscon#B360x362"
        },
        "2D58761B15": {
            "create date": "2022-04-08T13:40:28",
            "last use date": "2022-04-08T13:54:13",
            "name": "Phoscon#B1745x852"
        },
        "2E1232B15F": {
            "create date": "2022-04-16T22:48:12",
            "last use date": "2022-04-17T12:18:58",
            "name": "Phoscon#B1745x852"
        },
        "3074EFFE02": {
            "create date": "2021-10-13T10:16:50",
            "last use date": "2021-10-19T05:49:05",
            "name": "Phoscon#B360x362"
        },
        "3483DC445B": {
            "create date": "2021-10-31T10:35:49",
            "last use date": "2021-11-06T22:15:53",
            "name": "Phoscon#B360x362"
        },
        "37C5FD40BB": {
            "create date": "2022-11-27T00:00:29",
            "last use date": "2022-12-02T08:35:56",
            "name": "Phoscon#B360x408"
        },
        "3A0924AC80": {
            "create date": "2022-10-16T14:44:47",
            "last use date": "2022-10-23T20:54:01",
            "name": "Phoscon#B1904x920"
        },
        "4F60592E45": {
            "create date": "2021-12-29T18:58:35",
            "last use date": "2022-01-04T19:52:17",
            "name": "Phoscon#B360x362"
        },
        "5075D64957": {
            "create date": "2021-02-01T15:26:41",
            "last use date": "2021-02-02T22:25:00",
            "name": "Phoscon#B393x465"
        },
        "52D1945461": {
            "create date": "2021-08-20T21:18:25",
            "last use date": "2021-08-20T21:19:59",
            "name": "Phoscon#B393x419"
        },
        "53D28CEA6E": {
            "create date": "2022-11-02T18:30:58",
            "last use date": "2022-11-03T17:58:43",
            "name": "Phoscon#B360x408"
        },
        "57815C6C64": {
            "create date": "2022-07-29T22:31:40",
            "last use date": "2022-07-29T23:41:17",
            "name": "Phoscon#B1536x704"
        },
        "5AFB5ABE53": {
            "create date": "2022-07-14T21:16:03",
            "last use date": "2022-07-16T17:55:54",
            "name": "Phoscon#B360x360"
        },
        "5D1CDE8B01": {
            "create date": "2020-12-31T15:43:44",
            "last use date": "2021-01-07T02:38:56",
            "name": "openHAB"
        },
        "626A0C1670": {
            "create date": "2021-09-03T21:44:09",
            "last use date": "2021-09-04T11:28:49",
            "name": "openHAB"
        },
        "659E9A65DA": {
            "create date": "2021-10-31T10:37:17",
            "last use date": "2021-10-31T10:42:27",
            "name": "Phoscon#B1920x937"
        },
        "665B69BB62": {
            "create date": "2022-03-14T18:06:54",
            "last use date": "2022-03-14T18:29:06",
            "name": "Phoscon#B360x360"
        },
        "6ACFC4CD58": {
            "create date": "2021-11-07T13:13:23",
            "last use date": "2021-11-09T07:13:27",
            "name": "Phoscon#B360x362"
        },
        "6C64FE0F7D": {
            "create date": "2022-02-19T13:54:12",
            "last use date": "2022-02-19T14:34:17",
            "name": "Phoscon#B1920x880"
        },
        "6F4760D801": {
            "create date": "2022-11-02T21:48:33",
            "last use date": "2022-11-03T01:15:08",
            "name": "Phoscon#B1920x937"
        },
        "7317A2F03D": {
            "create date": "2022-02-20T11:58:13",
            "last use date": "2022-02-20T13:44:38",
            "name": "Phoscon#B360x362"
        },
        "791C513712": {
            "create date": "2022-04-28T18:32:55",
            "last use date": "2022-05-02T06:47:57",
            "name": "Phoscon#B1745x852"
        },
        "8062FB694A": {
            "create date": "2021-08-20T21:52:12",
            "last use date": "2021-08-22T18:44:53",
            "name": "Phoscon#B393x419"
        },
        "838DDED1A7": {
            "create date": "2021-09-04T19:06:00",
            "last use date": "2021-09-04T20:59:42",
            "name": "Phoscon#B1920x880"
        },
        "844E45121D": {
            "create date": "2021-09-13T18:09:45",
            "last use date": "2021-09-19T18:51:07",
            "name": "Phoscon#B1920x937"
        },
        "84B2331ECD": {
            "create date": "2021-10-18T06:06:18",
            "last use date": "2021-10-18T07:48:35",
            "name": "Phoscon#B1920x937"
        },
        "85E6AFEBBD": {
            "create date": "2022-10-24T21:36:56",
            "last use date": "2022-10-30T08:43:50",
            "name": "Phoscon#B1920x937"
        },
        "8DDED1A7FF": {
            "create date": "2021-11-15T18:30:44",
            "last use date": "2021-11-21T22:58:51",
            "name": "Phoscon#B360x362"
        },
        "91A806DA96": {
            "create date": "2021-09-03T15:43:36",
            "last use date": "2021-09-03T15:43:41",
            "name": "Phoscon#B1916x927"
        },
        "929ACF0D65": {
            "create date": "2022-02-08T15:16:45",
            "last use date": "2022-02-08T15:16:54",
            "name": "Phoscon#B1745x852"
        },
        "949D125781": {
            "create date": "2022-11-16T23:28:44",
            "last use date": "2022-11-16T23:29:25",
            "name": "Phoscon#B1920x937"
        },
        "96001C4C8D": {
            "create date": "2021-09-04T17:04:23",
            "last use date": "2021-09-04T18:43:45",
            "name": "Phoscon#B1536x704"
        },
        "96379623A0": {
            "create date": "2021-11-23T21:13:32",
            "last use date": "2021-11-30T13:56:23",
            "name": "Phoscon#B360x362"
        },
        "9D1257815C": {
            "create date": "2022-02-17T19:46:19",
            "last use date": "2022-02-17T19:46:19",
            "name": "Phoscon#B360x362"
        },
        "A2F2CBAB84": {
            "create date": "2022-01-06T23:54:09",
            "last use date": "2022-01-07T20:42:47",
            "name": "Phoscon#B1745x852"
        },
        "A534AD241F": {
            "create date": "2021-09-08T19:21:34",
            "last use date": "2021-09-15T19:29:11",
            "name": "Phoscon#B360x362"
        },
        "AB34A49D75": {
            "create date": "2021-10-05T13:46:50",
            "last use date": "2021-10-12T06:51:39",
            "name": "Phoscon#B1920x937"
        },
        "B8411F8E9E": {
            "create date": "2022-01-28T06:28:25",
            "last use date": "2022-02-04T07:13:59",
            "name": "Phoscon#B360x362"
        },
        "B8FDA4AC01": {
            "create date": "2021-12-14T18:04:15",
            "last use date": "2021-12-22T07:57:23",
            "name": "Phoscon#B980x985"
        },
        "BA6C130017": {
            "create date": "2022-05-23T19:14:59",
            "last use date": "2022-05-23T21:57:50",
            "name": "Phoscon#B360x360"
        },
        "C3B5205D77": {
            "create date": "2022-04-18T18:27:17",
            "last use date": "2022-04-25T18:23:25",
            "name": "Phoscon#B360x360"
        },
        "C4AB790461": {
            "create date": "2021-12-01T15:40:41",
            "last use date": "2021-12-09T21:07:16",
            "name": "Phoscon#B360x362"
        },
        "C792CF9899": {
            "create date": "2022-07-29T21:04:23",
            "last use date": "2022-07-29T21:09:49",
            "name": "Phoscon#B360x360"
        },
        "CE7FBAC206": {
            "create date": "2022-02-12T23:13:30",
            "last use date": "2022-02-19T08:55:04",
            "name": "Phoscon#B980x985"
        },
        "D90042E02A": {
            "create date": "2021-10-06T09:00:55",
            "last use date": "2021-10-12T17:44:43",
            "name": "Phoscon#B360x362"
        },
        "D9F9ED55FB": {
            "create date": "2022-10-24T18:23:27",
            "last use date": "2022-10-31T21:25:24",
            "name": "Phoscon#B360x360"
        },
        "DE8B01751A": {
            "create date": "2022-01-07T01:08:27",
            "last use date": "2022-01-07T08:48:26",
            "name": "Phoscon#B360x362"
        },
        "EB4133D999": {
            "create date": "2022-10-09T11:12:15",
            "last use date": "2022-10-09T18:58:17",
            "name": "Phoscon#B360x360"
        },
        "F98307BC04": {
            "create date": "2022-12-02T14:25:32",
            "last use date": "2022-12-02T14:26:16",
            "name": "Phoscon#B1920x937"
        },
        "FB67CAE6A2": {
            "create date": "2021-01-30T20:24:36",
            "last use date": "2021-01-30T20:24:38",
            "name": "Phoscon#B1536x704"
        },
        "FE87EECB67": {
            "create date": "2022-04-10T17:27:58",
            "last use date": "2022-04-10T17:32:18",
            "name": "Phoscon#B360x360"
        },
        "FF3046844F": {
            "create date": "2022-09-11T18:31:21",
            "last use date": "2022-09-11T19:01:38",
            "name": "Phoscon#B360x360"
        }
    },
    "wifi": "not-available",
    "wifiavailable": [],
    "wifichannel": "1",
    "wificlientname": null,
    "wifiip": "192.168.8.1",
    "wifimgmt": 0,
    "wifiname": null,
    "wifitype": "accesspoint",
    "zigbeechannel": 15
}

**Comment by CaeruleusAqua** [comment]
description.xml
```
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <URLBase>http://192.168.178.71:8080/</URLBase>
  <device>
    <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
    <friendlyName>Phoscon-GW (192.168.178.71)</friendlyName>
    <manufacturer>Royal Philips Electronics</manufacturer>
    <manufacturerURL>http://www.dresden-elektronik.de</manufacturerURL>
    <modelDescription>Philips hue compatible Personal Wireless Lighting</modelDescription>
    <modelName>Philips hue bridge 2015</modelName>
    <modelNumber>BSB002</modelNumber>
    <modelURL>http://www.dresden-elektronik.de</modelURL>
    <serialNumber>00212E04DB53</serialNumber>
    <UDN>uuid:c14ece50-ad71-48ee-808b-b46928250f92</UDN>
    <presentationURL>index.html</presentationURL>
    <iconList>
      <icon>
        <mimetype>image/png</mimetype>
        <height>48</height>
        <width>48</width>
        <depth>24</depth>
        <url>hue_logo_0.png</url>
      </icon>
    </iconList>
  </device>
</root>

```

**Comment by msinn** [comment]
Auf dem Hue Bridge Tab habe ich die "Modell ID" hinzugefügt. mach mal einen pull und sage, ob Du sie siehst und was da bei Dir steht.

Btw.: Wie erreiche ich Dich außerhalb von diesem PR? Auf Gitter scheinst Du nicht zu sein.

**Comment by msinn** [comment]
Ich bin gespant, da in den Config Daten bei Dir ```modelid": "deCONZ",```steht, 
in den xml Daten aber ```<modelNumber>BSB002</modelNumber>```ausgewiesen wird, was eine Philips Bridge v2 wäre

**Comment by CaeruleusAqua** [comment]
Model ID ist deCONZ
Am besten du schreibst mir eine email:
Julian.scholle@googlemail.com

**Pull request closed without merging**
