### PR TITLE
Enocean: restructure of learn methods

### PR DESCRIPTION
**Pull request by hasenradball**
Changes:
- move all learn methods in one "Learn methods section" at the end of the file
- correction of payload for send learn switch
- change logger.warning --> logger.info
- change logger-debug --> logger.info

- restructure existing learn methods like that:
1. define RORG
2. define PAYLOAD
3. send(RORG, PAYLOAD)
4. logger(RORG, PAYLOAD)
The benefit is the payload can be used directly in the send command an the logger.
logger-format: rorg = a5 / payload = [0xe0, 0x40, 0x0d, 0x80]
    
benefit of this changes is to define only one learn methods for future improvements and calculate in a switch...case construction thr rorg and payload.

### CODE REVIEW

**Comment by ohinckel** [comment]
Here's the diff (more readable):
```diff
diff --git a/enocean/__init__.py b/enocean/__init__.py
index ad0bf479..b7217740 100644
--- a/enocean/__init__.py
+++ b/enocean/__init__.py
@@ -250,7 +250,7 @@ class EnOcean(SmartPlugin):
         sender_id = int.from_bytes(data[-5:-1], byteorder='big', signed=False)
         status = data[-1]
         repeater_cnt = status & 0x0F
-        self.logger.debug("enocean: radio message: choice = {:02x} / payload = [{}] / sender_id = {:08X} / status = {} / repeat = {}".format(choice, ', '.join(['0x%02x' % b for b in payload]), sender_id, status, repeater_cnt))
+        self.logger.info("enocean: radio message: choice = {:02x} / payload = [{}] / sender_id = {:08X} / status = {} / repeat = {}".format(choice, ', '.join(['0x%02x' % b for b in payload]), sender_id, status, repeater_cnt))
 
         if (len(optional) == 7):
             subtelnum = optional[0]
@@ -434,10 +434,6 @@ class EnOcean(SmartPlugin):
         self.alive = False
         self.logger.info("enocean: Thread stopped")
 
-    def start_UTE_learnmode(self, id_offset=0):
-        self.UTE_listen = True
-        self.learn_id = id_offset
-        self.logger.info("enocean: Listeining for UTE package ('D4')")
         
     def _send_UTE_response(self, data, optional):
         choice = data[0]
@@ -448,9 +444,11 @@ class EnOcean(SmartPlugin):
         SubTel = 0x03
         db = 0xFF
         Secu = 0x0
+
         self._send_radio_packet(self.learn_id, choice, [0x91, payload[1], payload[2], payload[3], payload[4], payload[5], payload[6]],[SubTel, data[-5], data[-4], data[-3], data[-2], db, Secu] )#payload[0] = 0x91: EEP Teach-in response, Request accepted, teach-in successful, bidirectional
         self.UTE_listen = False
         self.logger.info("enocean: sending UTE response and end listening")
+
     def parse_item(self, item):
         if 'enocean_rx_key' in item.conf:
             # look for info from the most specific info to the broadest (key->eep->id) - one id might use multiple eep might define multiple keys
@@ -569,22 +567,6 @@ class EnOcean(SmartPlugin):
         self._send_common_command(CO_RD_NUMSECUREDEVICES)
         self.logger.info("enocean: Read number of secured devices")
 
-    def enter_learn_mode(self, onoff=1):
-        if (onoff == 1):
-            self._send_common_command(CO_WR_LEARNMODE, [0x01, 0x00, 0x00, 0x00, 0x00],[0xFF])
-            self.logger.info("enocean: entering learning mode")
-        else:
-            self._send_common_command(CO_WR_LEARNMODE, [0x00, 0x00, 0x00, 0x00, 0x00],[0xFF])
-            self.logger.info("enocean: leaving learning mode")
-
-    #This function enables/disables the controller's smart acknowledge mode
-    def set_smart_ack_learn_mode(self, onoff=1):
-        if (onoff == 1):
-            self._send_smart_ack_command(SA_WR_LEARNMODE, [0x01, 0x00, 0x00, 0x00, 0x00, 0x00])
-            self.logger.info("enocean: enabling smart acknowledge learning mode")
-        else:
-            self._send_smart_ack_command(SA_WR_LEARNMODE, [0x00, 0x00, 0x00, 0x00, 0x00, 0x00])
-            self.logger.info("enocean: disabling smart acknowledge learning mode")
 
         # Request all taught in smart acknowledge devices that have a mailbox
     def get_smart_ack_devices(self):
@@ -629,7 +611,7 @@ class EnOcean(SmartPlugin):
         packet += bytes([self._calc_crc8(packet[1:5])])
         packet += bytes(data + optional)
         packet += bytes([self._calc_crc8(packet[6:])])
-        self.logger.debug("enocean: sending packet with len = {} / data = [{}]!".format(len(packet), ', '.join(['0x%02x' % b for b in packet])))
+        self.logger.info("enocean: sending packet with len = {} / data = [{}]!".format(len(packet), ', '.join(['0x%02x' % b for b in packet])))
         self._tcm.write(packet)
 
     def _send_smart_ack_command(self, _code, data=[]):
@@ -696,13 +678,6 @@ class EnOcean(SmartPlugin):
         status2 = (BLC << 5) + (LRNB << 4) + (DSO << 2) 
         self._send_radio_packet(id_offset, 0xA5, [valve_position, TSP, status , status2])
 
-    def send_learn_radiator_valve(self, id_offset=0):
-        if (id_offset < 0) or (id_offset > 127):
-            self.logger.error("enocean: ID offset out of range (0-127). Aborting.")
-            return
-        self.logger.info("enocean: sending learn telegram for radiator valve")
-        self._send_radio_packet(id_offset, 0xA5, [0x00, 0x00, 0x00, 0x00])
-
 
     def send_dim(self,id_offset=0, dim=0, dimspeed=0):
         if (dimspeed < 0) or (dimspeed > 255):
@@ -762,6 +737,7 @@ class EnOcean(SmartPlugin):
         else:
             self.logger.error("enocean: sending command A5_38_08: error")
 
+
     def send_switch_D2(self, id_offset=0, rx_id=0, pulsew=0, on=0):
         if (id_offset < 0) or (id_offset > 127):
             self.logger.error("enocean: ID offset out of range (0-127). Aborting.")
@@ -784,33 +760,118 @@ class EnOcean(SmartPlugin):
         else:
             self.logger.error("enocean: sending command D2_01_07: error")
         
+
+####################################################
+### --- START - Definitions of Learn Methods --- ###
+####################################################
     def send_learn_dim(self, id_offset=0):
+        #self.logger.debug('enocean: send_learn_dim()')
+        # Prepare Data
+        rorg = 0xA5
+        # Only for Eltako FSUD-230V
+        payload = [0x02, 0x00, 0x00, 0x00]
+        # For other Eltako Dim Devices use this payload
+        #payload = [0xE0, 0x40, 0x0D, 0x80]
+
         if (id_offset < 0) or (id_offset > 127):
-            self.logger.error("enocean: ID offset out of range (0-127). Aborting.")
-            return
-        self.logger.info("enocean: sending learn telegram for dim command")
-        self._send_radio_packet(id_offset, 0xA5, [0x02, 0x00, 0x00, 0x00])
+            self.logger.error('enocean: ID offset with value = {} out of range (0-127). Aborting.'.format(id_offset))
+            return None
+        else:
+            self.logger.info('enocean: sending learn telegram for dim command with [ID-Offset], [RORG], [payload] / [{:#04x}], [{:#04x}], [{}]'.format(id_offset, rorg, ', '.join('{:#04x}'.format(x) for x in payload)))
+            self._send_radio_packet(id_offset, rorg, payload)
+            return None
+
 
     def send_learn_rgbw_dim(self, id_offset=0):
+        #self.logger.debug('enocean: send_learn_rgbw_dim()')
+        # Prepare Data
+        rorg = 0xA5
+        payload = [0xFF, 0xF8, 0x0D, 0x87]
+
         if (id_offset < 0) or (id_offset > 127):
-            self.logger.error("enocean: ID offset out of range (0-127). Aborting.")
-            return
-        self.logger.info("enocean: sending learn telegram for rgbw dim command")
-        self._send_radio_packet(id_offset, 0x07, [0xFF, 0xF8, 0x0D, 0x87])
+            self.logger.error('enocean: ID offset with value = {} out of range (0-127). Aborting.'.format(id_offset))
+            return None
+        else:
+            self.logger.info('enocean: sending learn telegram for rgbw dim command with [ID-Offset], [RORG], [payload] / [{:#04x}], [{:#04x}], [{}]'.format(id_offset, rorg, ', '.join('{:#04x}'.format(x) for x in payload)))
+            self._send_radio_packet(id_offset, rorg, payload)
+            return None
+
 
     def send_learn_switch(self, id_offset=0):
+        #self.logger.debug('enocean: send_learn_switch()')
+        # Prepare Data
+        rorg = 0xA5
+        payload = [0xE0, 0x40, 0x0D, 0x80]
+
         if (id_offset < 0) or (id_offset > 127):
-            self.logger.error("enocean: ID offset out of range (0-127). Aborting.")
-            return
-        self.logger.info("enocean: sending learn telegram for switch command")
-        self._send_radio_packet(id_offset, 0xA5, [0x01, 0x00, 0x00, 0x00])
+            self.logger.error('enocean: ID offset with value = {} out of range (0-127). Aborting.'.format(id_offset))
+            return None
+        else:
+            self.logger.info('enocean: sending learn telegram for switch command with [ID-Offset], [RORG], [payload] / [{:#04x}], [{:#04x}], [{}]'.format(id_offset, rorg, ', '.join('{:#04x}'.format(x) for x in payload)))
+            self._send_radio_packet(id_offset, rorg, payload)
+            return None
+
+
+    def send_learn_radiator_valve(self, id_offset=0):
+        #self.logger.debug('enocean: send_learn_radiator_valve()')
+        # Prepare Data
+        rorg = 0xA5
+        payload = [0x00, 0x00, 0x00, 0x00]
+
+        if (id_offset < 0) or (id_offset > 127):
+            self.logger.error('enocean: ID offset with value = {} out of range (0-127). Aborting.'.format(id_offset))
+            return None
+        else:
+            self.logger.info('enocean: sending learn telegram for radiator valve with [ID-Offset], [RORG], [payload] / [{:#04x}], [{:#04x}], [{}]'.format(id_offset, rorg, ', '.join('{:#04x}'.format(x) for x in payload)))
+            self._send_radio_packet(id_offset, rorg, payload)
+            return None
+
+
+    def start_UTE_learnmode(self, id_offset=0):
+        self.UTE_listen = True
+        self.learn_id = id_offset
+        self.logger.info("enocean: Listeining for UTE package ('D4')")
         
     def send_learn_actuator(self, id_offset=0):
+        #Prepare Data
+        rorg = 0xA5
+        payload = [0xFF, 0xF8, 0x0D, 0x80]
+        
         if (id_offset < 0) or (id_offset > 127):
             self.logger.error("enocean: ID offset out of range (0-127). Aborting.")
-            return
-        self.logger.info("enocean: sending learn telegram for actuator")
-        self._send_radio_packet(id_offset, 0xA5, [0xFF, 0xF8, 0x0D, 0x80])
+            return None
+        else:
+            self.logger.info('enocean: sending learn telegram for actuator with [ID-Offset], [RORG], [payload] / [{:#04x}], [{:#04x}], [{}]'.format(id_offset, rorg, ', '.join('{:#04x}'.format(x) for x in payload)))
+            self._send_radio_packet(id_offset, rorg, payload)
+        return None
+        
+        
+    def enter_learn_mode(self, onoff=1):
+        if (onoff == 1):
+            self._send_common_command(CO_WR_LEARNMODE, [0x01, 0x00, 0x00, 0x00, 0x00],[0xFF])
+            self.logger.info("enocean: entering learning mode")
+            return None
+        else:
+            self._send_common_command(CO_WR_LEARNMODE, [0x00, 0x00, 0x00, 0x00, 0x00],[0xFF])
+            self.logger.info("enocean: leaving learning mode")
+            return None
+
+            
+    # This function enables/disables the controller's smart acknowledge mode
+    def set_smart_ack_learn_mode(self, onoff=1):
+        if (onoff == 1):
+            self._send_smart_ack_command(SA_WR_LEARNMODE, [0x01, 0x00, 0x00, 0x00, 0x00, 0x00])
+            self.logger.info("enocean: enabling smart acknowledge learning mode")
+            return None
+        else:
+            self._send_smart_ack_command(SA_WR_LEARNMODE, [0x00, 0x00, 0x00, 0x00, 0x00, 0x00])
+            self.logger.info("enocean: disabling smart acknowledge learning mode")
+            return None
+
+##################################################
+### --- END - Definitions of Learn Methods --- ###
+##################################################
+
 
 #################################
 ### --- START - Calc CRC8 --- ###
```

**Comment by hasenradball** [comment]
Hello yes I know the diff.

The changes are tested.
I works and runs witout failure sincevI created the pr 87.


Best regards
Frank

Mit freundlichen Grüßen

Frank Häfele

**Comment by ohinckel** [comment]
A few notes about the patch:
* why are the methods `enter_learn_mode()` (and others) are now returning a `None` value explicitly?
* the code block after `if (id_offset < 0) or (id_offset > 127):` is repeated in a lot of methods which could be extracted to one validation method
* PR #44 contains additional changes on `README.md` (for more examples and documentation related to learinging mode) - are they missing here?

**Comment by hasenradball** [comment]
Hello ohinckel,

 

ok I ask all question you want.

Some Info about me. I work for a well known automotive company and have more than 10 years experience in well structured SW dewelopment.

 

When I do write SW, I try to do it in a perfect way. I know the opinion can differ.

 

To your questions:

 

a) I think it is a good coding style to return explicitly, and it is easy to understand the code for new phyton learners.

 

b) Yes you are totally right, this I want to improve in further PR. But from the past and my discussions with aschwith we discussed to make small improvement steps to be able to follow the changes.

My first PR includes all my improvemnts and in total aschwith had no time to review in total all refracture steps in once.

So I would do now small changes, but I want tot o ist step by step.

 

c) The change in readme.md in PR#44 was only formating text issues but I will rework the readme with the next changes additionally. So it is not necessary to do itexplizitly with PR#87.

 

Do you understand the changes in the Logger info?

 

The Goal ist o improve the learn and send methods like this:

Define rorg and payload before the learn and send method.

 

# Prepare Data

+        rorg = 0xA5

+        payload = [0xE0, 0x40, 0x0D, 0x80]

 

Then you are able to youse the same data int he send and the logger info:

 

For example the actual Switch learn method:

 

--

    def send_learn_switch(self, id_offset=0):

        #self.logger.debug('enocean: send_learn_switch()')

        # Prepare Data

        rorg = 0xA5

        payload = [0xE0, 0x40, 0x0D, 0x80]

 

        if (id_offset < 0) or (id_offset > 127):

            self.logger.error('enocean: ID offset with value = {} out of range (0-127). Aborting.'.format(id_offset))

            return None

        else:

            self.logger.info('enocean: sending learn telegram for switch command with [ID-Offset], [RORG], [payload] / [{:#04x}], [{:#04x}], [{}]'.format(id_offset, rorg, ', '.join('{:#04x}'.format(x) for x in payload)))

            self._send_radio_packet(id_offset, rorg, payload)

            return None

 

 

Maybe the diff you send me was not correct.

Does the diff work correctely?

 

I would prefer to use the file I pulled and not the dif out!

 

Do you have other questions?

 

Frank 

 

 

 

 

Von: ohinckel [mailto:notifications@github.com] 
Gesendet: Samstag, 11. November 2017 15:31
An: smarthomeNG/plugins
Cc: Frank Häfele; Author
Betreff: Re: [smarthomeNG/plugins] Enocean: restructure of learn methods (#87)

 

A few notes about the patch:

*	why are the methods enter_learn_mode() (and others) are now returning a None value explicitly?
*	the code block after if (id_offset < 0) or (id_offset > 127): is repeated in a lot of methods which could be extracted to one validation method
*	PR #44 <https://github.com/smarthomeNG/plugins/pull/44>  contains additional changes on README.md (for more examples and documentation related to learinging mode) - are they missing here?

**Comment by hasenradball** [comment]
Hello to,

 

would you like to view my logfile?

 

 

Von: ohinckel [mailto:notifications@github.com] 
Gesendet: Samstag, 11. November 2017 15:31
An: smarthomeNG/plugins
Cc: Frank Häfele; Author
Betreff: Re: [smarthomeNG/plugins] Enocean: restructure of learn methods (#87)

 

A few notes about the patch:

*	why are the methods enter_learn_mode() (and others) are now returning a None value explicitly?
*	the code block after if (id_offset < 0) or (id_offset > 127): is repeated in a lot of methods which could be extracted to one validation method
*	PR #44 <https://github.com/smarthomeNG/plugins/pull/44>  contains additional changes on README.md (for more examples and documentation related to learinging mode) - are they missing here?

**Comment by hasenradball** [comment]
So in addition I would to some other improvement PR for enocean related to your second comment. But I would make it step by step.

 

And I don’t want wait 6 month between each step.

 

Regards Frank

 

 

Von: ohinckel [mailto:notifications@github.com] 
Gesendet: Samstag, 11. November 2017 15:31
An: smarthomeNG/plugins
Cc: Frank Häfele; Author
Betreff: Re: [smarthomeNG/plugins] Enocean: restructure of learn methods (#87)

 

A few notes about the patch:

*	why are the methods enter_learn_mode() (and others) are now returning a None value explicitly?
*	the code block after if (id_offset < 0) or (id_offset > 127): is repeated in a lot of methods which could be extracted to one validation method
*	PR #44 <https://github.com/smarthomeNG/plugins/pull/44>  contains additional changes on README.md (for more examples and documentation related to learinging mode) - are they missing here?

**Comment by ohinckel** [comment]
First of all, don't get my feedback wrong. I'm really glad to see others are working on the project too. So thanks for your contributions!

I also don't want to make you sad. I like to tell other my opinion about the stuff others do. So I comment a lot of things. It's not to be a bad guy, it's all about to collaborate together to get a really cool product.

And I don't have any doubt about your knowledge or competence. We do not want to win a contest here, so I don't like to tell you details about my knowledge and when I started to write software.

But one thing: can you use the GitHub website to comment stuff in this issue? Your comments are getting very large and include a signature which does not help to improve readability.

**Comment by ohinckel** [comment]
OK, I just can merge this, without knowing if it is working. But I trust you in what you did, so I'll merge it.

**Comment by hasenradball** [comment]
ok thank you.
Then I am prepared to make the next improvement step.

**Pull request merged**
