### PR TITLE
smarthomeNG/plugin: enocean update 

### PR DESCRIPTION
**Pull request by hasenradball**
Updating enoceam class and test with Eltako Switch FSR61-230V

[plugin_Enocean.zip](https://github.com/smarthomeNG/plugins/files/884564/plugin_Enocean.zip)

### CODE REVIEW

**Comment by msinn** [comment]
I guess you made an error placing the PR.

The only files changes in this PR are from other plugin (whatsapp, hue, wol) but not from the enocean plugin.

**Comment by hasenradball** [comment]
Hello,

I am sorry, I think so. but what I have done wrong?
Can you give me a help?

**Comment by msinn** [comment]
First you should close this pull request. The next steps depend on the git client you use. For that I can only be of little help. I use SourceTree and in that graphical interface I can see/select which files would be includes in the PR.

**Comment by hasenradball** [comment]
Wrong repository. Sorry

**Pull request closed without merging**
