### PR TITLE
HUE-plugin: fix readme (lists are always required) and authorize-func

### PR DESCRIPTION
**Pull request by robert-budde**
Fix two severe flaws which are no good entry for novice users without debug-experience:
- Readme mentions wrong configuration for easy setups - lists are always required, checks are notr obvious or not working
- authorize-func crashes because of unproper conversion from bytes to string, after it fails at it does not use format mandated by https://www.developers.meethue.com/documentation/getting-started

### CODE REVIEW

**Comment by robert-budde** [comment]
this also applies to develop, yet it should be fixed in master for sure...

**Comment by msinn** [comment]
@ohinckel Kannst Du mal schauen was mit den travis tests schief gelaufen ist? Die Meldungen schreiben was von Ruby????

**Comment by ohinckel** [comment]
Die Aenderungen sind im `master` Branch gemacht und basieren auf einer alten Version (dort fehlt die Travis-Konfiguration und es wird ein falscher Build gestartet).

@robert-budde, kannst du bitte die aktuellen Aenderungen dir holen und ein rebase auf deinen Branch machen?

**Comment by msinn** [comment]
Parameter conversion for lists: parameters of type str are converted to lists (of len 1) is handled globally in lib.metadata.

Fixing the authorize function was done by a separate commit.

**Pull request closed without merging**
