### PR TITLE
Migrate to smartplugin

### PR DESCRIPTION
**Pull request by hebe2k**

### CODE REVIEW

**Comment by psilo909** [comment]
you should use has_iattr und get_iattr_value instead of item.conf[xyz'] (https://github.com/smarthomeNG/smarthome/wiki/SmartPlugin#multiinstanzf%C3%A4higkeit-von-plugins) 

are u willing to adapt this, although you dont have a MI plugin?

**Comment by ohinckel** [comment]
If no notice already: the PR is against the `master` branch not the `develop` branch. Should be closed and recreated against the `develop` branch.

**Comment by hebe2k** [comment]
@ohinckel I closed it and will create a new one again develop, thanks for the hint.

**Comment by hebe2k** [comment]
created new PR against develop, see #46

**Pull request closed without merging**
