### PR TITLE
AVDevice plugin: Implemented webinterface, updated methods and logging

### PR DESCRIPTION
**Pull request by onkelandy**
does currently not work with 1.5.1 master :(

### CODE REVIEW

**Comment by msinn** [comment]
What part of the plugin doesn‘t work with v1.5.1?

**Comment by onkelandy** [comment]
The scheduler_change part was not working correctly in 1.5.1 master.

**Comment by ohinckel** [comment]
@onkelandy, can you resolve the conflicts?

**Comment by onkelandy** [comment]
conflict resolved. But I need to do one more commit, just a second.

**Comment by ohinckel** [comment]
@msinn, any objections against a merge?

**Comment by onkelandy** [comment]
Für die Feature-List wären's dann wohl:
- Diverse Optimierungen und Anpassungen
- Konfigurationsfile für Denon AVR1100
- Webinterface

**Pull request merged**
