### PR TITLE
Initial Version of telegram

### PR DESCRIPTION
**Pull request by gamade**
First functional version of telegram - a plugin gateway to telegram instant messaging system

### CODE REVIEW

**Comment by msinn** [comment]
Hi,

I tried to install your plugin, but haven't succeeded.

First problem for me was:

A token with double quotes gives me the exception:
```
2017-04-16  12:03:22 ERROR    Main         Plugin telegram exception: 'ascii' codec can't encode character '\u201c' in position 9: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/shng_dev/lib/plugin.py", line 90, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/local/shng_dev/lib/plugin.py", line 144, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/shng_dev/plugins/telegram/__init__.py", line 52, in __init__
    self.logger.warning("Telegram bot is listening: {0}".format(self._bot.getMe()))
  File "/usr/local/lib/python3.4/site-packages/telepot/__init__.py", line 401, in getMe
    return self._api_request('getMe')
  File "/usr/local/lib/python3.4/site-packages/telepot/__init__.py", line 397, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.4/site-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python3.4/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.4/site-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.4/http/client.py", line 1116, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.4/http/client.py", line 973, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 9: ordinal not in range(128)
```
 I use yaml configuration files and yaml doesn't support double-quotes ("). I had to modify the plugin.yaml ans specify the token either without quotes or with single quotes. Since double-quotes are not needed in .conf files, I would suggest to modify the README and remove the double-quotes.

After fixing the first problem I ran into a problem with **`trusted_chat_ids`**. I don't know what they are. They are not explained in the README, so I commented out that line.

When **`trusted_chat_ids`** are not specified, I run into the following exception:
```
2017-04-16  12:07:13 ERROR    Main         Plugin telegram exception: invalid literal for int() with base 10: 'none'
Traceback (most recent call last):
  File "/usr/local/shng_dev/lib/plugin.py", line 90, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/local/shng_dev/lib/plugin.py", line 144, in __init__
    exec("self.plugin.__init__(smarthome{0}{1})".format("," if len(arglist) else "", argstring))
  File "<string>", line 1, in <module>
  File "/usr/local/shng_dev/plugins/telegram/__init__.py", line 56, in __init__
    self._chat_ids = list(map(int, trusted_chat_ids.split(',')))
ValueError: invalid literal for int() with base 10: 'none'
```
**`none`** is the default value, you specify in
```
    def __init__(self, smarthome, token='dummy', trusted_chat_ids='none'):
```

Here I am stuck. What are **`trusted_chat_ids`** good for and how do I get hold of them?

**Comment by msinn** [comment]
You should update the copyright notice. It refers to smarthome.py and the github repository of the old version.

**Comment by msinn** [comment]
It would be good to be able to define two messages (at least for bool items). This way you could send one message if the item gets True and another if the item gets False.

If I get it right, now I have to define two items (one for each message), setting enforce_updates for each of them and trigger one Item if my bool-item gets True and trigger the other one if my bool-item gets False.

**Comment by msinn** [comment]
It would be good to implement a better error handling. Today a message was not sent, but the log showed a couple of exceptions for that message:

```
2017-04-17  18:55:10 ERROR    Main         Item wohnung.stati.abwesend: problem running <bound method Telegram.update_item of <plugins.telegram.Telegram object at 0x7f421be6df98>>: ('Connection aborted.', ConnectionResetError(104, 'Die Verbindung wurde vom Kommunikationspartner zurückgesetzt'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/local/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.4/ssl.py", line 751, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.4/ssl.py", line 623, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/shng_dev/lib/item.py", line 714, in __update
    method(self, caller, source, dest)
  File "/usr/local/shng_dev/plugins/telegram/__init__.py", line 111, in update_item
    self._bot.sendMessage(cid, msg)
  File "/usr/local/lib/python3.4/site-packages/telepot/__init__.py", line 408, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python3.4/site-packages/telepot/__init__.py", line 397, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python3.4/site-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python3.4/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.4/site-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/site-packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.4/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/local/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.4/ssl.py", line 751, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.4/ssl.py", line 623, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Die Verbindung wurde vom Kommunikationspartner zurückgesetzt'))
```

The exception need to be caught and it would be good to try again to send out the message.

**Comment by gamade** [comment]
Hi,
I'ld like to make some changes to the code and readme. What is the right way to update the pull request? (sorry, my fist git project ;) )

**Comment by msinn** [comment]
I see two options: 

1. Update the files in your repository. That should be relected in this PR as well.
2. If 1. doesn't work: Close this PR and create a new PR with the changed files.

**Comment by msinn** [comment]
Looks ok so far. 

For the next PR you should extend/complete the README.md.:
- The explanation of the plugin parameter 'name' is a bit short. (From reading I don't understand what it does)
- The parameter welcome_msg is not documented at all

**Comment by Foxi352** [comment]
Hallo @gamade,

Seems to be a problem if an unknown user sends "/subscribe" to the bot to get his ID.

Line 210: `self._bot.sendMessage(tmp_chat_id, "Welcome at %s. Please register your ID: [%d]" % (self._name, tmp_chat_id))`

That line does not work. If you remove the %s and self._name it does work:
`self._bot.sendMessage(tmp_chat_id, "Please register your ID: [%d]" % (tmp_chat_id))`

I have no clue why the self._name does not work here as it works two line above on the "you are already signed up" line ....

Serge

**Pull request merged**
