### PR TITLE
Stateengine Plugin 2.0.0

### PR DESCRIPTION
**Pull request by onkelandy**
introducing new features and improvements

### CODE REVIEW

**Comment by Morg42** [comment]
Works fine here, intermediate complaints about missing graphviz (same installation) occur. More investigation needed...

**Comment by Morg42** [comment]
looks good here.

Only the empty "issues" logs might be removed...? ;-)

**Comment by onkelandy** [comment]
I'll include the initial config check in the web interface.. do some extended testing and then hopefully merge.

**Comment by onkelandy** [comment]
I merge now as this release is at least testable ;)
TODO:
- implement released_by, se_use and issue handling in web interface
- further extend issue handling of values and actions, etc.
- refactor code to make everything cleaner and more pythonic

**Pull request merged**
