### PR TITLE
Kodi SmartPlugin

### PR DESCRIPTION
**Pull request by ssudholt**
This PR renames the XBMC plugin to Kodi and updates it to a smart plugin.

In addition, the PR also adds some functionality in terms of controlling Kodi (e.g. Play, Pause, Stop,...).

### CODE REVIEW

**Comment by onkelandy** [comment]
@ssudholt I've seen you are working on a denon plugin. I've spent a lot of time in my avdevice plugin that now also fully supports Denon. Could you please test my plugin and give me feedback as github issue or on knx forum? Thanks!
https://github.com/onkelandy/plugins/tree/avdevice_plugin

Starting to test your kodi plugin right away.. Thanks!

**Comment by onkelandy** [comment]
Problem when there are no favorites defined:
``
2017-11-08  10:23:34 ERROR    sh.connections Method sh.connections exception: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 446, in _task
    obj()
  File "/usr/local/smarthome/lib/connection.py", line 90, in check
    obj.connect()
  File "/usr/local/smarthome/lib/connection.py", line 400, in connect
    self._connected()
  File "/usr/local/smarthome/lib/connection.py", line 224, in _connected
    self.handle_connect()
  File "/usr/local/smarthome/plugins/kodi/__init__.py", line 103, in handle_connect
    item_dict = {elem['title']: elem for elem in result['favourites']}
TypeError: 'NoneType' object is not iterable
``

**Comment by onkelandy** [comment]
In line 156 there is a self._send that doesn't exist.

After changing that line it's possible to set the volume just fine. Reading media, state, etc. also works. What would be great: init alls values on startup because the values stay empty when starting smarthomeNG. 

By the way - any chance to make it compatible for 1.3 master branch? The get_shortname function doesn't exist there as well as the get_paramater_value. Would also love to see Stop, Play, Pause ;)

Thanks alot!

**Comment by ssudholt** [comment]
Thanks for your tests. I fixed the bugs you mentioned and added Play/Pause and Stop functionality. There was already functionality for sending inputs such as up and down keys on the keyboard. Updated the docs also.

**Comment by ssudholt** [comment]
The should actually be filled at start at, except for the player dependend stuff if nothing is playing.

Regarding the compatibility with 1.3: should that exist along side or rather make it compatible to 1.3 now and switch to 1.4 once its released? I would think that switching back and forth now would be quite the hassle.

**Comment by psilo909** [comment]
the code should be able to "work" with items that are not configured::

```
2017-11-08  18:00:20 ERROR    sh.connections   Method sh.connections exception: 'NoneType' object is not subscriptable          
Traceback (most recent call last):                                                                                              
  File "/python/smarthome_dev/lib/scheduler.py", line 446, in _task                                                             
    obj()                                                                                                                       
  File "/python/smarthome_dev/lib/connection.py", line 90, in check                                                             
    obj.connect()                                                                                                               
  File "/python/smarthome_dev/lib/connection.py", line 400, in connect                                                          
    self._connected()                                                                                                           
  File "/python/smarthome_dev/lib/connection.py", line 224, in _connected                                                       
    self.handle_connect()                                                                                                       
  File "/python/smarthome_dev/plugins/kodi/__init__.py", line 97, in handle_connect                                             
    params=dict(properties=['volume', 'muted']))['result']                                                                      
TypeError: 'NoneType' object is not subscriptable                                                                               
2017-11-08  18:00:30 ERROR    sh.connections   Method sh.connections exception: 'NoneType' object is not subscriptable          
Traceback (most recent call last):                                                                                              
  File "/python/smarthome_dev/lib/scheduler.py", line 446, in _task                                                             
    obj()                                                                                                                       
  File "/python/smarthome_dev/lib/connection.py", line 90, in check                                                             
    obj.connect()                                                                                                               
  File "/python/smarthome_dev/lib/connection.py", line 400, in connect                                                          
    self._connected()                                                                                                           
  File "/python/smarthome_dev/lib/connection.py", line 224, in _connected                                                       
    self.handle_connect()                                                                                                       
  File "/python/smarthome_dev/plugins/kodi/__init__.py", line 97, in handle_connect                                             
    params=dict(properties=['volume', 'muted']))['result']                                                                      
TypeError: 'NoneType' object is not subscriptable     
```

**Comment by psilo909** [comment]
from what i understand, the plugin uses the kodi web interface. i would prefer to have a more advanced framework such as requests to be used instead of the old outdated connection.py library which is currently written newly by @Foxi352

**Comment by psilo909** [comment]
Bye the way: i now defined all items from README but still get the errors above.. my Kodi is running on 8080 and is accesable via webinterface there.. i also adjusted my plugin.yaml..  a proper exception would give at least a hint, what could be wrong

**Comment by psilo909** [comment]
the web interface of kodi also allows me to set user and (optionally) password, which looks not supported by plugin

**Comment by ssudholt** [comment]
@psilo909 the plugin makes use of the TCP transportation in order to get messages to and from Kodi (see the [Kodi JSON-RPC API](http://kodi.wiki/?title=JSON-RPC_API)). This transportation uses port 9090 by default. From what it looks like you are trying to use the HTTP transportation which is why it fails. I'm going to update the documentation to make sure users known which port they should use. 

Do you experience the same errors when using the TCP port?

**Comment by psilo909** [comment]
@ssudholt that is important to know.. at least the GUI on my enigma2 receiver did only display activiation buttons for the web interface and the upnp interface, but a json-rpc api. need to check this on the level of command line this evening.

hence, there was also no interface listening on port 9090.

a better documentation and error handling would be appreciated in any way!

**Comment by ssudholt** [comment]
Ok, I updated to documentation.

Also, I made a major change to how inputs can be send to Kodi (Play, Pause, Stop,...). They are now controlled by in item which has a `kodi_item@...: input` field and is of type string. Setting this item to an allowed input command triggers input events on Kodi. See the documentation for more infos..

**Comment by psilo909** [comment]
i tried to activate the json rpc interface as described in http://kodi.wiki/?title=JSON-RPC_API
however i still cannot connect on port 9090

is there any curl request i could test?!

**Comment by ssudholt** [comment]
A quick Google search gives me the following:
`curl -s --data-binary '{"jsonrpc": "2.0", "method": "JSONRPC.Ping", "id":1}' -H 'content-type: application/json;' http://<kodi host>:9090/jsonrpc`
If that doesn't work you can try an HTTP GET reuqest to check whether the JSON-RPC API is available at all:
`http://<kodi host>:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22method%22:%22JSONRPC.Ping%22,%22params%22:{},%22id%22:16}`
It is, however, strange that the port doesn't even open for you. Whats your Kodi version?

**Comment by psilo909** [comment]
@ssudholt access is working now.. i just dont like the ERRORs in case KODI is not running. thought the server is running at least in the background, when kodi is stopped. but it looks like it is only reachable when it is (visually) started

**Comment by onkelandy** [comment]
Thanks for the updates! Looks pretty promising right now. play, stop, etc. work like a charm. But volumeup and volumedown don't work in my setup..

Would be cool to fetch the cover of the running movie like here:
https://forum.kodi.tv/showthread.php?tid=237963

;) But in general I think the plugin already rocks! Thanks!

**Comment by psilo909** [comment]
@onkelandy is the plugin getting a connection when the kodi application is not running in the GUI? do you have any idea of there is a background service or something? i dont like connection error messages on each shng restart.

**Comment by psilo909** [comment]
just an info: 
the plugin is doing a request every 10 minutes and spamming my logfile..ö
yes i know: the error is correct when the kodi app is not running and we have similar things in the enigma2 plugin when the device is completely turned off. but in case of kodi it is just an application that is not started, so these messages will appear all the time (!!!!)

grafik

there is a way to avoid the connection retries: e.g. adding a helper item that stops the plugin. but you could also include an "on/off" item by DEFAULT. in case the item is false, the plugin stops sending requests towards kodi.

**Comment by onkelandy** [comment]
@psilo909 I'm running KODI on libreelec Pi image. As soon as I kill the GUI the plugin tells me there is no active player. But I don't get any connection messages right now..?

**Comment by psilo909** [comment]
@onkelandy from what i see this error message expects a result.. i suppose on my enigma2 device it cant even establish the connection. but in my view this is an issue of connection handling, which could be caught as exception. so also in cases with connections that cant be established, this message is shown...

**Comment by onkelandy** [comment]
I definitely agree that an (in)active option/item would be great! I've always had the connection error message when my kodi Pi was shut down.. pretty annoying indeed.

But as soon as the connection lib in sh.py is optimized the implementation of that library is fine, right? Or does it expect complete different code?

**Comment by psilo909** [comment]
Hi, i dont know what @Foxi352 is coding, i think he already pushed a first version to DEV, but under a different name.
But the lib wont solve the connection errors we have here. normally. in my view the lib should give an exception that can be handled in the plugin  and - instead of an error - it could just write a warning as it is no error in this context.. anyway. it could also be reached by switching to requests for example.

**Comment by ohinckel** [comment]
To be able to close PR #23 we should include the newly introduced `shutdown` command from it in this PR too. @ssudholt do you think you can integrate it in this PR?

**Comment by ssudholt** [comment]
I tried to incorporate the current feedback as good as possible in the last commit.
For this, I switched the TCP handling to be done by the new lib.network classes. If a connection cannot be established after five tries, the Kodi server is assumed to be offline and no further connection attempts are made. The plugin can then be asked to retry connecting to Kodi by calling the `connect_to_kodi()` method.

Alternatively, the user can also supply an item with the `kodi_item` tag `on_off`. If there doesn't exist a connection and the item is set to `True`, the plugin tries to establish a connection. If the item is set to `False`, a shutdown command is issued to Kodi.

I have yet to extensively test the new features and have only done some very rudimentary testing. Feedback by you would, again, thus greatly appreciated.

**Comment by ssudholt** [comment]
@Foxi352  By the way, in switching to new the lib.network classes, I stumbled upon the problem that the Tcp_client class does not allow for determining when the receive thread was started, i.e., when a duplex connection was established. This would be something nice for me to have since commands send to Kodi sometimes expect a response. If you think this is a good feature as well I can add it in this PR or another one.

**Comment by onkelandy** [comment]
I've copied the network lib to my smarthome.py 1.3 master installation and changed the following lines to make it compatible with 1.3. I don't think there is any disadvantage so maybe you could change it to make the plugin work in 1.3 (of course manual copying of network.py is necessary, but that is no big deal..)
line 88:     def __init__(self, sh, host, port):

New lines under line 94:
```
        try:
            host=self.get_parameter_value('host')
            port=self.get_parameter_value('port')
        except:
            self.logger.debug('Parameter analysis not supported.. continuing')
```
kodi_tcp_connection line:
```
        self.kodi_tcp_connection = Tcp_client(host,
                                              port,
```

So far it seems to work. But the logging should include the plugin name as module name. Right now it says:
 TCP_Receive  Kodi receiving: 
 TCP_Connect  TCP connection to 10.0.0.151:9090 failed

**Comment by onkelandy** [comment]
I got some problem with the "active player" anyhow as I am using a switchable power socket for my kodi device (Raspi).

If the socket is off and no connection is possible I get the 5 connection retries. Perfect.
As soon as the socket is on and I change kodi_item on_off to on I get the following problem:
```
2017-11-26  09:51:48 DEBUG    TCP_Connect  Starting connection cycle for 10.0.0.151
2017-11-26  09:51:48 DEBUG    TCP_Connect  Connecting to 10.0.0.151 using IPv4 10.0.0.151 on TCP port 9090 without autoreconnect
2017-11-26  09:51:48 INFO     TCP_Connect  Connected to 10.0.0.151 on TCP port 9090
2017-11-26  09:51:50 DEBUG    Main         Kodi sending: {"jsonrpc":"2.0","id":2,"method":"JSONRPC.Ping"}
2017-11-26  09:51:50 DEBUG    TCP_Receive  Kodi receiving: {'id': 2, 'jsonrpc': '2.0', 'result': 'pong'}
2017-11-26  09:51:50 DEBUG    Main         Kodi sending: {"jsonrpc":"2.0","id":3,"params":{"properties":["volume","muted"]},"method":"Application.GetProperties"}
2017-11-26  09:51:50 DEBUG    TCP_Receive  Kodi receiving: {'id': 3, 'jsonrpc': '2.0', 'result': {'volume': 90, 'muted': False}}
2017-11-26  09:51:50 DEBUG    Main         Kodi sending: {"jsonrpc":"2.0","id":4,"params":{"properties":["window","path","thumbnail","windowparameter"]},"method":"Favourites.GetFavourites"}
2017-11-26  09:51:50 DEBUG    TCP_Receive  Kodi receiving: {'id': 4, 'jsonrpc': '2.0', 'result': {'favourites': None, 'limits': {'start': 0, 'end': 0, 'total': 0}}}
2017-11-26  09:51:50 WARNING  Main         Item heimkino.kodi.favorites: value {} does not match type bool. Via Kodi None
2017-11-26  09:51:50 DEBUG    Main         Kodi sending: {"jsonrpc":"2.0","id":5,"method":"Player.GetActivePlayers"}
2017-11-26  09:51:50 DEBUG    TCP_Receive  Kodi receiving: {'id': 5, 'jsonrpc': '2.0', 'result': []}
2017-11-26  09:51:50 INFO     Main         Kodi: no active player found.
```
The "no active player found" is somehow correct as the Raspi is just booting and kodi might not be running yet. But imho it a connection is made there should be an option to look for active players every x seconds. What do you think? Should be optional of course.

Furthermore.. I start a video on Kodi and it runs just fine. The plugin receives the following data:
```
2017-11-26  09:56:30 DEBUG    TCP_Receive  Kodi receiving: {'jsonrpc': '2.0', 'params': {'data': {'item': {'id': 287, 'type': 'episode'}, 'player': {'speed': 1, 'playerid': 1}}, 'sender': 'xbmc'}, 'method': 'Player.OnPlay'}
```
But trying to control Kodi with the plugin (stopping, pausing) still doesn't work as it thinks there is still no active player. Imho the plugin should try to get the active player again as soon as it receives anything, right?

Now to the real problem.. Kodi is running and playing. The "power on_off" item is on, but no active player recognized. So I trigger that item again and hope the plugin now finds an active player. But I get these messages:
```
2017-11-26  10:06:51 ERROR    Main         Already connected to 10.0.0.151, ignoring new request
2017-11-26  10:06:53 DEBUG    Main         Kodi sending: {"jsonrpc":"2.0","id":10,"method":"JSONRPC.Ping"}
2017-11-26  10:06:55 ERROR    Main         Kodi JSON-RPC API not available. Did you connect to the TCP port (default: 9090)?
2017-11-26  10:06:55 DEBUG    Main         Plugin 'wz': stop method called
2017-11-26  10:06:55 INFO     Main         Closing connection to 10.0.0.151 on TCP port 9090
```

From that moment on the plugin is gone. I'd have to restart smarthome :(

'wz' is the name of the instance, not of the plugin by the way.

Thanks for looking into that!

**Comment by Foxi352** [comment]
It is a bit eary to use the network lib for production. And by production i mean the imminent release of 1.4. That's why the lib starts with these two bit fat warning lines :-) It was more pushed into dev for other developers to have a look into it and to give feedback. It was not yet meant to be used.

The problem is, i want SHNG to be multiplatform as much as possible. By multiplatform i mean Linux, MacOS and Windows, even though we'll probably only officially support Linux. The network lib will be 90% reponsible for the project to be multiplatform.

That's why i am currently rewriting the network lib entirely to use the new Python asyncio mechanism. Under the hood this new standard lib uses epoll for Linux, kqueue for Mac and good old select for Windows. That means everything uses that new lib it will automatically multi platform, well at least from network com's side. The problem is, asyncio is only fully supported and working for Python >= 3.5, so we have to wait for SHNG 1.5 to officially use it (according to our wiki page with supported python versions).

This rewrite might change the interfaces, means method parameters and parameters passed to callbacks. Even though these changes will hopefully be minor. So we discussed in Gitter (i think it was only @msinn and myself) that i will probably remove it from the develop branch just before the 1.4 release, and put it back for the 1.5 release.

But i am glad someone is testing it :-) (I have myself running a modified version of CLI and KNX plugins using the new lib for testing).

What i suggest in your case is, that you copy the lib into your plugin directory for now and make it 1.3 compatible if you want (anyway changes seem to be minor). Once we are on 1.5 dev branch and the rewrite towards asyncio is done, you can switch the plugin to the official lib/network.py and remove it from your plugin's dir. So we immediately have a working plugin for testing (after maybe some minor changes).

**Comment by ohinckel** [comment]
> It was not yet meant to be used.

I think it is not a real problem to use this network library in the kodi plugin because:
a) this plugin is really new and nobody will use it currently
b) we could mark the plugin as experimental for the xbmc plugin replacement
c) it would help if we already have some plugins migrated to this library to find problems as early as possible

Further I think @ssudholt already spend a lot of time, so we should keep the current version. I would vote for just declare the kodi plugin expermiental and mention that it requires Python 3.5.

**Comment by Foxi352** [comment]
No objections to use it, but my suggestion to copy it into the kodi plugin directory for now is still standing. I want to retire the network lib from the lib folder before the 1.4 release to avoid further misunderstandings (and usage) and to avoid to break the whole system when i push the asyncio version. The only more work to be done is to copy it into the kodi plugin folder and to change the import statement.

Don't get me wrong, i appreciate the work done by @ssudholt and i would love to continue usage of the new lib into the brand new Kodi plugin, so both can mature together. And as i also have a Vera / Kody system i will probably use the plugin myself. But as the 1.4 release is just one step away i feel we might introduce unneeded instabilities into a brand new 1.4 release if more authors start using the lib before it is ready.

@ohinckel Do you see any problem copying the lib into the kodi folder and removing it from the lib dir until after the 1.5 release ?

**Comment by Foxi352** [comment]
> By the way, in switching to new the lib.network classes, I stumbled upon the problem that the Tcp_client class does not allow for determining when the receive thread was started, i.e., when a duplex connection was established. This would be something nice for me to have since commands send to Kodi sometimes expect a response. If you think this is a good feature as well I can add it in this PR or another one.

@ssudholt I am not really sure i get the picture here. The receive thread is started as soon as the connection is made. And the connection has a callback. Do you mean there are timing problems (i.e. it takes some time before the thread is up after the connected callback) and want another callback or instance variable when the receive_thread is up and running ? It is the exact right time to fill in a wish list for the lib, so just try to make me understand what you need :-)

Beside that, was it simple enough to use the lib without any example to copy from ? Was the documentation clear enough ? I am open to all kind of feedback ...

**Comment by psilo909** [comment]
currently there seems to be a conflict in this PR?!

**Comment by ohinckel** [comment]
Yes, thats because #23 integrated changes to file `xbmc/__init__.py` which was deleted in this PR.

@ssudholt, maybe you can rebase your stuff and keep the old `xbmc` plugin beside of the new `kodi` plugin. This would also makes it easier for XBMC/Kodi users to migrate to the new plugin. Removing the `xbmc` plugin completely forces them to migrate directly after a SHGN update.

**Comment by onkelandy** [comment]
It looks like the plugin is blocking everything during connection retries. So startup of plugins and evaluations after kodi plugin gets delayed for 30 seconds..

**Comment by onkelandy** [comment]
Right after the connection error mentioned above I get the following error when I use "turn_on" another time:
```
2017-12-01  07:46:46 ERROR    Main         Already connected to 10.0.0.151, ignoring new request
2017-12-01  07:46:48 DEBUG    Main         Kodi sending: {"jsonrpc":"2.0","id":11,"method":"JSONRPC.Ping"}
2017-12-01  07:46:48 ERROR    Main         Item heimkino.kodi.power: problem running <bound method Kodi.update_item of <plugins.kodi.Kodi object at 0x76348dd0>>: name 'msg' is not defined
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/network.py", line 498, in send
    self._socket.send(message)
ConnectionResetError: [Errno 104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/smarthome/lib/item.py", line 714, in __update
    method(self, caller, source, dest)
  File "/usr/local/smarthome/plugins/kodi/__init__.py", line 241, in update_item
    self.connect_to_kodi()
  File "/usr/local/smarthome/plugins/kodi/__init__.py", line 193, in connect_to_kodi
    self.on_connect()
  File "/usr/local/smarthome/plugins/kodi/__init__.py", line 144, in on_connect
    result = self.send_kodi_rpc(method='JSONRPC.Ping')
  File "/usr/local/smarthome/plugins/kodi/__init__.py", line 305, in send_kodi_rpc
    self.kodi_tcp_connection.send((json.dumps(data, separators=(',', ':')) + '\r\n').encode())
  File "/usr/local/smarthome/lib/network.py", line 502, in send
    self.logger.warning("No connection to {}, cannot send data {}".format(self._host, msg))
NameError: name 'msg' is not defined
```

**Comment by onkelandy** [comment]
Beim Setzen von Mute scheint alles zu klappen, aber wenn ich Mute wieder ausschalte, passiert leider nichts :( Passiert das nur mir so?
```
2017-12-02  08:53:39 DEBUG    Main         Plugin 'wz': update_item ws called with item 'heimkino.kodi.mute' from caller 'Visu', source '10.0.0.13:57217' and dest 'None'
2017-12-02  08:53:39 DEBUG    Main         Kodi sending: {"id":7,"jsonrpc":"2.0","method":"Application.SetMute","params":{"mute":true}}
2017-12-02  08:53:39 DEBUG    TCP_Receive  Kodi receiving: {'id': 7, 'jsonrpc': '2.0', 'result': True}
```

**Comment by ssudholt** [comment]
Thanks for all the feedback:
@onkelandy I'll look into the active player issue. From the log, it seems you used mute as a toggle item as well. The mute item, however, is treated as real boolean value meaning `True` activates mute and `False` deactivates it. Could you try that and see what happens?

@Foxi352 The problem is that I want to send a JSON-RPC command right after connect. This command requires a response from the server. The `on_connect` callback is called after the connection has been established but before the receive thread is started. This way, if I send a command in the `on_connect` callback method, it won't be able to receive an answer as the receive thread is not running at this point. Hence, I would need either to have the receive thread started before the call to the callback function or have another callback possibility indicating that the connection has been established and the receive thread was started also. I'm currently handling this problem by simply waiting 2 seconds after I send the connect command before checking whether a connection was succesfully established but this is kind of ugly and I think a callback would be nicer here.

@ohinckel That makes a lot of sense, I'll rebase and keep the old XBMC plugin for the time being.

**Comment by Foxi352** [comment]
@ssudholt Ok, got you. Sounds good, i will include a callback possibility and a property like the is_connected. So you'll have the choice what to use.

**Comment by Foxi352** [comment]
@ssudholt 
https://github.com/smarthomeNG/smarthome/commit/ecc5b8cbb0985eab97c9c0107ca745475581f511

**Comment by msinn** [comment]
Zur Nutzung der network.lib: Eigentlich sollte die lib im Release 1.4 nicht Bestandteil sein. (Noch nicht fertig und anderes min. Python Requirement). Eine reine Kennzeichnung des Plugins als "experimental" erscheint mir etwas zu Support-trächtig. Ich hätte folgenden Vorschlag:

Die network.lib in das Release aufnehmen und das Plugin "schützen":

Systematisch könnte man so ein Problem dadurch abfangen, dass in den Metadaten der Plugins z.B. eine **minpythonver** angegeben wird und der Plugin Loader die Version gegen die laufende Version prüft. Die Änderung wäre mit jedoch, da das Release von v1.4 recht kurz bevorsteht, zu groß um sie noch zu implementieren.

Als Quick-and-Dirty Schutz könnte ich die Prüfung der Python Version in die `__init__` Routine des Plugins einbauen und bei zu altem Python das Laden des Plugins geordnet unterbinden (ja, eine solche Möglichkeit gibt es mit shNG v1.4 😄).

Meinungen?

**Comment by ohinckel** [comment]
Da wir bereits die Lib im develop haben wird es umstaendlich das aus dem Release herauszuhalten. Von daher erstmal mit releasen - in der API Doc steht, dass sie fuer das 1.5 Release gedacht ist. Es gibt auch eigentlich nicht viel, was diese Lib schon verwendet (glaube eigentlich nichts, ausser das, was @Foxi352  testweise schon umgestellt hat, wie z.B. CLI Plugin - das aber, soweit ich weiss, nur ein im in einem lokalen Branch/Checkout).

Das Plugin koennte man auch erstmal nicht mergen und erst nach dem 1.4 Release in den develop mergen. Dann waere es erst fuer die naechste Version verfuegbar - denke das kann man auch verkraften.

Bin mir nicht sicher, ob das mit der **minpythonver** in der Plugin-Konfig eine gute Idee ist. Das ist eher etwas, was allgemein fuer shng gelten sollte und nicht fuer einzelne Teile/Plugins. Irgendwann hat man dann evtl. einige Bedingungen, die sich widersprechen koennten (und Dependency/Version Checks und deren Aufloesung ist nicht immer trivial - mal abgesehen davon ob der Benutzer dann weiss, was er im Konfliktfall machen muss).

**Comment by msinn** [comment]
Ok, dann sollten wir aber scharf darauf achten, dass wir keine Plugins in den Master bekommen, die ein neueres Python erfordern als der Core.

**Comment by Foxi352** [comment]
Momentan wird sie nur vom Kodi Plugin verwendet. KNX und CLI hatte ich nur lokal quick & dirty umgestellt um real life Testszenarien zu haben. Das war nie zum pushen gedacht, jedenfalls nicht so bald. Mein Idee war die lib nicht mit ins 1.4 release zu nehmen. z.B. einfach nach dem release branch die lib entfernen oder sie schon vorher zu entfernen. Da sie aber jetzt von einem Plugin genutzt wird muss man IMHO entscheiden ob das Kodi Plugin schon stabil genug für's release ist (hab's noch nicht testen können wegen Zeitmangel). Wenn ja könnte man wie oben geschrieben die lib einfach in's Plugin Verzeichnis moven für's 1.4 release. Quasi als Bestandteil vom Kodi Plugin. Nach dem release kann man sie wieder in das lib Verzeichnis zurückmoven. Es wäre nur das Import im plugin zu ändern.

**Comment by onkelandy** [comment]
Das Plugin hat leider noch massive Probleme, wenn die Verbindung zum Player zwischen drin oder va. zu Beginn nicht vorhanden ist. 

Besonders drastisch wird es, wenn der Rechner zwar erreichbar ist, Kodi aber (noch) nicht läuft. Siehe meine Kommentare oben.

**Comment by psilo909** [comment]
Kann ich bestätigen. Würde es noch nicht ins 1.4er aufnehmen

**Comment by Foxi352** [comment]
Gut. Dann lib raus aus dem dev, Kodi noch nicht mergen.
Sobald release auf 1.4 ge"branched* ist lib wieder rein in's dev und Kodi mergen ?

**Comment by msinn** [comment]
Du kannst die network.lib ruhig im dev lassen. Ich schmeiße sie beim Bau des Releases raus.

**Comment by Foxi352** [comment]
Da wir ja jetzt mehr oder weniger 1.5 dev sind könnte man dieses mergen ?

**Comment by ohinckel** [comment]
Bin mir nicht sicher, aber ich habe in Erinnerung, dass es mit dem Plugin noch Probleme gibt. Sollten wir das trotzdem mergen (weil es erstmal im `develop` landet)? Ich denke das Plugin sollte halbwegs stabil sein damit wir es mergen koennen, oder?

**Comment by onkelandy** [comment]
Prinzipiell kann es halt eher getestet werden, wenn's auch irgendwo verfügbar ist ;)
Hauptproblem ist, wenn man zwischendurch mal Kodi bzw. den Rechner abschaltet. Lässt man alles laufen, läuft auch das Plugin brauchbar, soweit ich das gesehen habe.

Vielleicht kann sich @ssudholt noch drum kümmern?

**Comment by ssudholt** [comment]
Entschuldigt bitte die späte Rückmeldung. Ich werde in der nächsten Zeit leider etwas wenig Zeit haben am Plugin zu arbeiten. Ich bemühe mich, dass ich schnellst möglich die Fehler behebe, die ihr noch gelistet habt.

**Comment by onkelandy** [comment]
Irgendwelche News und Fortschritte @ssudholt ?

**Comment by psilo909** [comment]
@ssudholt same question from my side. it would be a good thing to include the plugin in our upcoming release. we also now have a blog in which you could write a short howto for the plugin. https://www.smarthomeng.de/blog

**Comment by onkelandy** [comment]
Knock knock ;)

**Comment by psilo909** [comment]
Bitte auch eine Info wenn nicht mehr weitergearbeitet wird. Entweder muss sich dann jemand dem Thema annehmen oder der PR geschlossen werden.

**Comment by bmxp** [comment]
Could we find an end with a working PR? It would be great to have this plugin in SHNG 1.6 which knocks at the doors. @ssudholt could you have a look at the current state?

**Comment by Morg42** [comment]
I'll take up this plugin. Will need a bit to get acquainted, then find out what needs to be done. Kodi test environment is available :)

**Comment by onkelandy** [comment]
With SmartDevice as a base, right ;)?

**Comment by Morg42** [comment]
What else? :D

**Pull request merged**
