### PR TITLE
Database Plugin: avoid error on dump when connection is lost

### PR DESCRIPTION
**Pull request by onkelandy**

### CODE REVIEW

**Comment by onkelandy** [comment]
A message in the log and esp. in the web interface would be good indeed. Right now the exception leads to an "endless hang" when dumping from the webif and an 500 error.

**Comment by ohinckel** [comment]
OK, in this case we should check why it hangs. Maybe there is another locking/releaseing issue.

**Comment by ohinckel** [comment]
Are we able to reproduce the error to identify why it hangs? In case of an exception an error should be logged.

**Comment by onkelandy** [comment]
I'm not sure if we can easily recreate the problem. I just know I had it and the simple fix fixed it ;) I've added error messages now.

**Comment by ohinckel** [comment]
Of course solving problems by just ignoring them would "fix" it. But still, the error is just ignored and I think ignoring errors is the wrong solution (like try/catch block around the whole program and not handling the exception at all).

If we can't reproduce the problem, does it still exist?

**Pull request closed without merging**
