### PR TITLE
SMLX Plugin: Changes / Improvement

### PR DESCRIPTION
**Pull request by sisamiwe**
- changed way to make sure, that just one thread for read and parse is active (THX to bmxp, ohinckel)
- Code cleanup
- Adapt code to by compatible with Python 3.7
- Bumped to version 1.1.7

### CODE REVIEW

**Review by bmxp — COMMENTED** [review]
Looks fine on first sight, just have not time to check it in real live currently. If it runs at your place, go ahead!

**Comment by CaeruleusAqua** [comment]
Is this going to be merged soon? I have rewritten half the plugin and extended by asyncio (polling is optional still possible).
This will unfortunately give a bunch of merge conflicts. oO

**Comment by bmxp** [comment]
@CaeruleusAqua maybe you should make your enhancement a version 2.0 since it uses asyncio

**Comment by Morg42** [comment]
Tested and works fine so far. Merging now, if problems arise later, we can still check for hidden errors...

**Pull request merged**
