### PR TITLE
[enocean]: Teach-In enocean actors via SHNG backend 

### PR DESCRIPTION
**Pull request by hasenradball**
- add file <enocean_learn.py>
- update README.md
- small corrections in README.md

### CODE REVIEW

**Comment by hasenradball** [comment]
PR tested via DolphinView.

**Comment by aschwith** [comment]
I appreciate your pull request. However, too many files were changed. I do not have the time to review every single change. I suggest you split your pull request into single requests with clear and obvious contributions, e.g. start by updating the readme only. Thanks.

**Comment by hasenradball** [comment]
If you had have a real look at the files, which have been changed you could see that the only file which has been changed was the README.md.
One other file was added in the folder scripts!
I see you are not interesed havin a real look at the changes!

The file which was added could be used to trigger the learn routine via backend.

--> See the comments ist was testet via Dolphin.
Thanks.

**Comment by aschwith** [comment]
Learn routins can already be triggered via the webinterface of the Enocean plugin. There is no need to copy and paste logic files.

**Comment by hasenradball** [comment]
How does it work over the Webif?
Is there a need to update you documentation?

**Comment by aschwith** [comment]
Yes, please try out the learn procedure via the webinterface. If you see potential for improvement of the respective documentation, your input is very much appreciated. Did you manage to access the webinterface of the Encoean plugin? If you have problems, please let us know in the Enocean plugin forum.

**Comment by hasenradball** [comment]
WOW , it looks great and easy simple!
where does the Webif know the actuators and the learn sequences are they extracted by the implemented actors?
Or is this handled separately.

Is this correct that if the backend is available I have already the Webif available?

**Comment by hasenradball** [comment]
Please update the enocean Readme.md to describe the possibilty for the learning via webif. This prevents other users from developing code which is not necessary!
Thank you

**Comment by hasenradball** [comment]
One Question to the Webif interface of enocean.
would it not be better to set the default value of the id-offset to zero?
```
<input type="input" class="form-control mb-1" id="input-offset" placeholder="{{ _('ID Offset') }}" value="1" maxlength="3" style="width: 50px;">
```

**Comment by aschwith** [comment]
Yes, the correlation between one actor and the learn sequence are hardcoded in the webif template. The lists mainly consists of Eltako actuators which I use. Feel free to add whatever actor you have in use. I would immediately accept a pull request. 
Regarding the default id offset, I think I remember the first valid offset value is one and not zero. I figured people might be confused having an invalid default value zero.
There should be a small hint in the readme.md that there is another teach in possibility via the webif. Sure, that could be detailed. Again, please add the information that you are missing and issue a SEPARATE pull request, which I would accept. Thanks. 
Last but not least, lets shift this conversation to the forum, where a lot more people can follow us. Talk to you there.

**Comment by hasenradball** [comment]
Hi thank you for your Information.
I could test the WebIf Interface with dolphin view.
Works fine. Meassage is received vai USB receiver.

**Pull request closed without merging**
