### PR TITLE
AVM Plugin:

### PR DESCRIPTION
**Pull request by sisamiwe**
- Update Docu
 - Update WebIF
 - Connect to Smarthome Devices via AHA-Interface (tested mit Fritz 440, Comet Dect) (therefore Plugin AVM smarthome can be depreciated)
 - implement call deflections (tested mit Fritzbox 7530)
 - Rename Parameter "index" to "avm_tam_index"
 - Code Cleanup (add new functions to mimimize code repetitions)
 - Improve error handling

### CODE REVIEW

**Comment by aschwith** [comment]
Eventually, I had time to look at the pull request und test the changes. Very good contribution!

Only breaking change is the need for the heating radiator valve attribute to be changed from "set_temperature" to "set_target_temperature". That is ok for me. The rest works fine as expected. I opt for a merge.

**Comment by onkelandy** [comment]
Maybe datatables could be implemented for the web interface, @sisamiwe ?
See https://github.com/smarthomeNG/smarthome/blob/develop/doc/user/source/entwicklung/plugins/webinterface_filling_webinterface.rst

**Comment by bmxp** [comment]
Yes, datables would be a good enhancement. But shouldn't we first merge this and update avm again afterwards with datatables?

**Comment by sisamiwe** [comment]
> Maybe datatables could be implemented for the web interface, @sisamiwe ? See https://github.com/smarthomeNG/smarthome/blob/develop/doc/user/source/entwicklung/plugins/webinterface_filling_webinterface.rst
Done. Pls check it.

**Comment by onkelandy** [comment]
WebIF looks fine.. except all these entries..
$('#smarthomeitemtable').DataTable( {"paging": false, fixedHeader: true} );

should actually be
```
$('#smarthomeitemtable').DataTable( {} );
```

Anyhow, now the whole PR is a huge mess.. Please delete and re-create on basis of a fresh branch.

**Comment by msinn** [comment]
As @onkelandy wrote:

> Anyhow, now the whole PR is a huge mess.. Please delete and re-create on basis of a fresh branch.

Beside changing the avm plugin, your PR contains changes to the kodi and the stateengine plugin **and**
tries to set the version of the development branch to master!!!

Please close this PR and make a new (clean) one.

**Comment by sisamiwe** [comment]
Due to the mess I created I'm closing that PR and will create a new one

**Pull request closed without merging**
