### PR TITLE
New Plugin for SNMP queries

### PR DESCRIPTION
**Pull request by sisamiwe**
Hi,
I've created a new plugin for quering information via snmp from other computers.
Since this is my first plugin and pull request I'm open for comments.

Michael

### CODE REVIEW

**Comment by psilo909** [comment]
The PR contains a lot of viessmann stuff?! Is this correct?

**Comment by bmxp** [comment]
I think you should first get the latest version of develop branch and then give a PR onto that. We can not merge the PR the way it is now...

**Comment by psilo909** [comment]
In any way i would love to test the plugin.. i also started a snmp plugin a time ago but failed largely in understanding snmp ;-)

**Comment by sisamiwe** [comment]
@bmxp 

I think I've got the latest version of the develop branch now. Should I do a new PR?

In regards to the Viessmann stuff. This should not be part of that PR since this new plugin is not finished, yet. I just pushed the current status to my git.

**Comment by sisamiwe** [comment]
@psilo909 

This plugin is very simple since it is also me first plugin. The request for done using the oids.
I've used the request since a longer time as a logic. Now I've transfered it to a plugin also to learn how to write plugins.

**Pull request closed without merging**
