### PR TITLE
fixing typo error in KNX Plugin

### PR DESCRIPTION
**Pull request by ssudholt**
This PR fixes a minor typing error in two methods from the KNX plugin

### CODE REVIEW

**Comment by ohinckel** [comment]
This should go into `develop` branch first. Or is this a hotfix?

**Comment by bmxp** [comment]
As this can be circumvented with setting and getting the attribute directly it is now a hotfix. It can be merged however to develop branch.

**Comment by ssudholt** [comment]
My apologies, I wasn't aware of the correct branch to pull request to. Shall I close this one and re-submit it to the develop branch?

**Comment by bmxp** [comment]
Yes, please do so.

**Pull request closed without merging**
