### PR TITLE
Added a new plugin for Kostal PIKO - Inverters with http/json communi…

### PR DESCRIPTION
**Pull request by datenschuft**
Added a new plugin for Kostal PIKO - Inverters with http/json communication.

since UI-version 6 json communication is supported.

### CODE REVIEW

**Comment by ohinckel** [comment]
Things to think about for this PR:
* it wants to be merged into `master` instead of `develop`
* the version number should be something with 1.3.x - see [version numbers](https://github.com/smarthomeNG/smarthome/wiki/Versionsnummern)
* make use of the `has_iattr()` and `get_iattr_value()` methods instead of accessing `item.conf` dict directly

Some design questions:
* Could this be combined with the existing kostal plugin by specifying a `device` setting to decide if it is the other way or the JSON way to access the data?
* Should we start using capitals in the package/module directories? See also [PEP-8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)

**Comment by datenschuft** [comment]
Now i'm using smarthomeng ver 1.2 and the Plugin works with this version. So i decided to set the version to 1.2.1
I will install version 1.3 the next days.
If i combine the json communication with the existing kostal-plugin, i could not test the old communication. (Not good)
Master branch-sorry. Could i change the pr to the dev branch?

I'll try my best to, do a better job (next time)

**Comment by ohinckel** [comment]
Don't get it wrong: I only want to share my opinion about your PR. I'm glad to see people developing plugins, so thanks for your contribution!

For the version you should use 1.3 since 1.2 is already released but does not contain your plugin.

If you want somebody to test the kostal plugin, then you found one: me.

Changing your development base from master to develop is a little bit harder. But it should be possible to apply your patches on-top of the develop branch (e.g. you can use "git format-patch" and "git apply").

**Comment by datenschuft** [comment]
Hi there, 
I have rewritten the Kostal plugin.
It should support now the old communication HTML-part and the new JSON communication.
Could you test the plugin bevore I create a new PR. 
https://github.com/datenschuft/plugins/tree/kostal-piko-json-support/kostal
This is my first plugin and i have not written a lot of python code... 
So please give me a feedback.

Hint: a contributing howto would be fine.

**Comment by psilo909** [comment]
@datenschuft welcome here (i was the one asking u to use the SMA EM code :) ). i am happy you are now also using our framework.

i will also have look at your plugin the next days. i can only check the code, as i dont have this inverter

**Comment by ohinckel** [comment]
I'll test it the next days. Thanks for your support! If you want you can also create a net PR for this.

**Comment by ohinckel** [comment]
Just tested the new kostal plugin a little bit and so far it is working as expected but I had some notes/remarks about it. It would be helpful if you could create a new PR with the implementation so that I can write down my comments into the new PR.

**Comment by psilo909** [comment]
Some feedback: in case you are able to look there you could add a thread to the knx-user-forum.de as support thread to the plugin and document it in the README

i also think there is a function in the utils.py to check IPs for validity (self.ip = ip)

**Comment by datenschuft** [comment]
I'll try to update the code in the next days and try to include your comments/feedback; 
New PR to develop branch ?

**Comment by ohinckel** [comment]
Yes, new PR against the develop branch. I have some more feedback, but I want to write it down into the new PR instead of using this (closed) PR.

**Comment by ohinckel** [comment]
For your information: I just added some comments to the new PR #61.

**Pull request closed without merging**
