### PR TITLE
NUT - new plugin

### PR DESCRIPTION
**Pull request by 4d4mu**
Hi,
Recently I created this new plugin to connect with NUT - Network UPS Tools daemon. So far works fine with my server, now it's time to share :) I tried to make it SmartPlugin and multiinstance (to work with more than one ups device).
Can anyone test it? :)

4d4mu

### CODE REVIEW

**Comment by psilo909** [comment]
unfortunately cant test ist.. where you could modify is the plugin version. you are writing 1.3.0, the last digit in fact is the plugin version, so 1.3.0.1 would be plugin version 0.1.. version "0" is perhaps a bit misleading

**Comment by psilo909** [comment]
thx... in my opinion i could just merge it.. but it would be good if someone could test it before (i cant :-/)

**Comment by 4d4mu** [comment]
Thanks. Actually, nut allows to create dummy devices from text files, so anyone with nut-compatible OS and some time and goodwill can test it :) I've tested multi-instance mode with one real device and one dummy. Or if I'm the only user right now, I guess we can merge it

**Comment by psilo909** [comment]
well give it some more days, but being the only user also accounts for some of my plugins ;-) at least i think so.. so even if there are bugs, these can be discussed when you are not the only user anymore

**Comment by psilo909** [comment]
ah and sorry that i 4got about: a support thread in the knx user forum reference from the readme as link and an entry in https://github.com/smarthomeNG/smarthome/wiki/Liste-der-Plugins (after the plugin has been merged) would be nice. in case u are not using the forum, i dont mind

**Comment by 4d4mu** [comment]
Currently I'm not using this forum. Is it all German or English posts are allowed?
BTW, i found similar plugin - apcups. NUT is compatible with many APC devices, so maybe someone can test it... @cstrassburg?

**Comment by ohinckel** [comment]
If there are no other users I think we can merge this. I guess it will not break anything. A support thread linked in the readme file would be nice!

**Comment by psilo909** [comment]
as he is not using the forum, i dont think we can demand that thread.. merging is ok for me.

**Comment by 4d4mu** [comment]
thanks

**Pull request merged**
