### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by henfri**
Hallo, 

ich habe den Parameter cycle zur Readme hinzugefügt und den Bereich der items für die Vorhersage korrigiert.

Gruß,
Hendrik

### CODE REVIEW

**Comment by ohinckel** [comment]
Really want to merge this into `master`?

**Comment by msinn** [comment]
This PR contains a couple of errors:

- wug_datatype for plugin.yaml / plugin.conf: This makes no sense
- for forcast values the forcast days are missing
- forcast values only defined for the current day and not for the days to come

**Comment by henfri** [comment]
> wug_datatype for plugin.yaml / plugin.conf: This makes no sense

Why?

>for forcast values the forcast days are missing
Yes. No change to the current status.
I just corrected/clarified the rain probability vs. the rain amount.

**Comment by msinn** [comment]
Short answer: Because it is not implemented.
Long answer: wug_datatype is implemented as an attribute for individual items. So, it can be used in items.ymal / items.conf. It is not a plugin parameter. So it is not to be used in plugin.yaml / plugin.conf.

What should it do in the plugin.yaml?

**Pull request closed without merging**
