### PR TITLE
SNMP Plugin

### PR DESCRIPTION
**Pull request by sisamiwe**
Hi,

this is the 2nd try to create PR.
Michael

### CODE REVIEW

**Comment by psilo909** [comment]
again all the viessmann stuff inside :-/

**Comment by psilo909** [comment]
oh and AVM etc.. the pr should only contain the commits related to your plugin

**Comment by psilo909** [comment]
in the worst case: check out develop, put in your plugin, do ONE commit of everything and then do the PR

**Comment by sisamiwe** [comment]
Can I do a PR just for one directory?

**Comment by psilo909** [comment]
if you take the develop branch as is (fresh checkout) and then just add and commit your plugin directory, it will be only for one directory..

**Pull request closed without merging**
