### PR TITLE
AVM Plugin:

### PR DESCRIPTION
**Pull request by sisamiwe**
- Correct "_update_smarthome_items"
 - stay at plugin version 1.6.1

### CODE REVIEW

**Comment by aschwith** [comment]
@sisamiwe: Conflict resolution is no longer necessary. Your fix is included in commit 0741dd71f5a2d9bbda25d2ff174cd0e5389afdb1. Thanks! This one can be closed.

**Comment by psilo909** [comment]
hmm i am not getting the 404s again :-/

**Comment by psilo909** [comment]
2022-02-16  19:12:55 ERROR    plugins.avm      wlan_repeater_1750_galerie@: AHA command error code: 404
2022-02-16  19:13:01 ERROR    plugins.avm      wlan_repeater_1750_front@: AHA command error code: 404

(because its querying my repeaters for aha devices, which do not have webpage for aha devices)

**Comment by sisamiwe** [comment]
I will try to solve the remaining issues. Also I have found some other bugs, which where not detected yet. 
Nevertheless I will work in an further improved version.
Therefore this PR will be closed.

**Pull request closed without merging**
