### PR TITLE
Support D2_01_12 - simple 2 channel switch

### PR DESCRIPTION
**Pull request by DrGEH**
- Rewrote my changes from #140 to work on top of new updates to this branch, relatively small changes and should be able to be merged quickly

- tested and confirmed working on my setup with D2_01_12 switch from NodOn

### CODE REVIEW

**Comment by ohinckel** [comment]
Can you please change this PR to merge into `develop` branch`?

**Comment by DrGEH** [comment]
@ohinckel done, sorry about that. I merged the latest version of master into my fork before creating this PR so the 41 commits that develop is behind are included in this PR as well now. I hope that's not a problem.

**Comment by ohinckel** [comment]
The PR looks a little bit strange, but that should not be a problem for the merge.

@robert-budde / @aschwith, according to the `plugin.yaml` you're the maintainer. Could you please have a look at it and decide if we can merge this? Thanks!

**Comment by DrGEH** [comment]
We had some problems with the IDE and whitespaces but everything should
be.fine now.

**Pull request closed without merging**
