### PR TITLE
XBMC: added shutdown command

### PR DESCRIPTION
**Pull request by smaugs**
added shutdown command. one can now use xbmc_send = shutdown in items.conf

### CODE REVIEW

**Comment by msinn** [comment]
Could you document the additioal feature in the README.md?

**Comment by onkelandy** [comment]
Any chance to update the plugin furthermore? Right now it's very rudimentary.. or maybe I just don't get it how to use it? You can only send volume and mute command, right?

**Comment by ohinckel** [comment]
Adding the new command to the documentation would be really nice. If added we could merge it.

@onkelandy, yes only these commands were supported. Which commands do you need? I think supporting the whole system is really much work. So we should first - if somebody want - focus on most used or important commands.

**Comment by onkelandy** [comment]
Play, pause, stop would be the minimum for me. As a matter of fact I've implemented stop, but I had problems with implementing the play command somehow (can't remember why). 

Showing the currently playing title would also be nice - as well as the power commands (esp. restart)
Then an implementation in the VISU would start to make sense ;)

Thanks a lot.

**Comment by smaugs** [comment]
Sorry I was pretty busy the last weeks - I'll document the shutdown command this weekend. Maybe I'll have a look at stop/play - see if I have the same problem(s) as onkelandy :)

**Comment by ohinckel** [comment]
Updating the documentation would be enough in the first step to merge this PR. Please update the documentation and create a new PR for the additional commands.

**Comment by ohinckel** [comment]
@smaugs already updated the documentation? After this we can merge and close this PR. Thanks for your support!

**Comment by psilo909** [comment]
also waiting for a documentation update. .yaml examples in the README would be nice

also a migration to SmartPlugin and the recommended use of the logger as attribute would be nice

**Comment by onkelandy** [comment]
@psilo909 This one could be killed because it's replaced by:
https://github.com/smarthomeNG/plugins/pull/95

**Comment by psilo909** [comment]
@onkelandy what do you mean with killed? close the PR?

**Comment by onkelandy** [comment]
The kodi plugin replaces this XBMC plugin.. so actually the whole XBMC plugin could/should be removed.

**Comment by ohinckel** [comment]
Merged the current state of this now into `develop`. Further development should go to new `kodi` plugin - see #95.

**Pull request merged**
