### PR TITLE
fixed play/stop status update when using player groups

### PR DESCRIPTION
**Pull request by onkelandy**
When using player groups plugin or player sync the status of a synced player wasn't updated correctly.

### CODE REVIEW

**Comment by ohinckel** [comment]
I guess you need to rebase your changes. Is this PR still in development or ready to merge after resolving the conflicts?

**Comment by onkelandy** [comment]
*argl* two in one.. ;) The avdevice is still in development. Didn't want to push that, just the squeezebox plugin. Can you resolve the conflict?

**Comment by ohinckel** [comment]
So what do you want to be part of this PR? You can reset the branch to one of the old commit.

I suggest you to:
* checkout a new branch by using `git checkout -b new-stuff`, which will create a new branch with the current version (to avoid losing changes by just keeping them in a different branch then `develop`)
* reset the `develop` branch to the version you want by using `git checkout develop` (switch back to `develop` branch)  and resetting to commit by using `git reset --hard 6a6bd560ea2c365a8fb2385241675d5a49c95800` (reset index and tree back to given commit)

After this you will have a `develop` branch where HEAD is on the given commit and a new branch containing additional stuff committed after the given commit.

Then just (force) push the develop again to the remote (this will update this PR too). There should be no conflicts and we could merge this PR.

This should only include the changes for the `squeezebox` plugin and we could merge. After this you could checkout the different branch from above and merge it back to `develop` pushing again to the remove and creating a new PR (if you want) for the `avdevice` plugin.

**Comment by onkelandy** [comment]
created a clean PR.. thanks!

**Pull request closed without merging**
