### PR TITLE
some plugin updates

### PR DESCRIPTION
**Pull request by ThomasCr**

### CODE REVIEW

**Comment by psilo909** [comment]
hmm it would have helped to just have 1 pr for each plugin. this way it makes it more hard to accept the PR changes

**Comment by psilo909** [comment]
anyway: the changes look ok for me in a first view - but it still would be easier to split the modifications to existing plugins to a completely new plugin.

is anyone able to test the RTR changes and the zwave plugin? for me the question is if it is mature enough to include it to our 1.4 release or not

**Comment by ThomasCr** [comment]
I run that code on my home (with the multiple stop items).

**Comment by bmxp** [comment]
I have RTR plugin running in office and will test if there are any problems with it asap but not before Monday...

**Comment by ThomasCr** [comment]
For those who want to test the zwave plugin and has not already installed the openzwave components: I made a Ubuntu PPA with compiled version of all was is needed. It is compiled for current LTS Versions, but it runs most also on Debian. I also switched the arm compilation on, so that it is compatible with raspberry pi and others. 

https://launchpad.net/~t.c/+archive/ubuntu/zwave

**Comment by msinn** [comment]
I have Z-Wave components (which i have to look for in the cellar) and I have ordered an OpenZwave compatible USB controller. Probably I will be able to test between x-mas and newyear.

**Comment by psilo909** [comment]
@msinn which brand did you buy? perhaps i will also do so to be able to test... at least i have several colleagues using zwave whom i want to convince to use shng ;)

**Comment by msinn** [comment]
I ordered **Z-Wave.Me USB Smart Home Stick made for My Cloud2™ by WD, Z-Wave Plus** for 28 Euros

**Comment by psilo909** [comment]
@msinn ok thx :) i am also orderning now :) any ideas for a zwave device which wont be completely useless in my house due to the knx installation?!

**Comment by msinn** [comment]
My Z-Wave stick arrived. Now I can start testing after X-Mas

**Comment by psilo909** [comment]
Mine also arrived... Unfortunalty i only have the stick but now device ;)

**Comment by Foxi352** [comment]
My entire house was controlled by z-wave until i replaced everything by knx. Sadly i gave away all my equipment. But two of us should be enough to test 😉

**Comment by ohinckel** [comment]
Someone was already able to test the z-wave plugin?

**Comment by psilo909** [comment]
i will merge now. Next time: please do not mix diverse PRs of diverse Plugins

**Pull request merged**
